/*
 * decomp-source: func_80076BE0
 * matched VMA 0x80076BE0  file 0x673E0  span 0x30 bytes / 12 words
 * evidence: docs/evidence/func_80076BE0/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80076BE0.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_80095854 PE_DECOMP_PTRGLOBAL(0x80095854u, unsigned int)
#define D_80095850 PE_DECOMP_PTRGLOBAL(0x80095850u, unsigned int)

/* ── verbatim matching leaf (src/func_80076BE0.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: D_80095854 */
/* shimmed by pe_guest_decomp.h: D_80095850 */
unsigned int func_80076BE0(unsigned int a0) {
    *D_80095854 = a0 | 0x10000000;
    return *D_80095850 & 0xFFFFFF;
}

