/*
 * decomp-source: func_80050708
 * matched VMA 0x80050708  file 0x40F08  span 0x20 bytes / 8 words
 * evidence: docs/evidence/func_80050708/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80050708.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* ── verbatim matching leaf (src/func_80050708.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: func_80064C54 */

void func_80050708(int value) {
    func_80064C54(value + 0x1F);
}

