/*
 * decomp-source: func_80087050
 * matched VMA 0x80087050  file 0x77850  span 0x40 bytes / 16 words
 * evidence: docs/evidence/func_80087050/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80087050.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009D2E0 PE_DECOMP_SCALAR(0x8009D2E0u, volatile unsigned int)

/* ── verbatim matching leaf (src/func_80087050.c) ───────────────────────── */

/*
 * func_80087050 — wait for / test the low bit of a status word.
 *
 * VRAM 0x80087050 / file 0x77850 / size 0x40 (16 words).
 * ROM: asm/disc1/77850.s.
 *
 * Retail layout:
 *   if (a0 == 0) { while (D_8009D2E0 & 1) ; return 0; }
 *   return D_8009D2E0 & 1;
 * The a0==0 loop is emitted first (lower addresses) with an explicit `j` past
 * the a0!=0 arm to the shared epilogue. D_8009D2E0 must be volatile: without
 * it cc1 hoists the second load out of the loop and the test reuses a stale
 * value.
 */
/* shimmed by pe_guest_decomp.h: D_8009D2E0 */

int func_80087050(int a0) {
    if (a0 == 0) {
        while (D_8009D2E0 & 1)
            ;
        return 0;
    }
    return D_8009D2E0 & 1;
}

