/*
 * decomp-source: func_800506E8
 * matched VMA 0x800506E8  file 0x40EE8  span 0x20 bytes / 8 words
 * evidence: docs/evidence/func_800506E8/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800506E8.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* boundary: func_80058AA8 has no pc_port implementation yet */
#define func_80058AA8(...) PE_D_COMP_BOUNDARY0("func_80058AA8", 0x80058AA8u)


/* ── verbatim matching leaf (src/func_800506E8.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: func_80058AA8 */

void func_800506E8(void) {
    func_80058AA8();
}

