/*
 * decomp-source: func_8006F2C4
 * matched VMA 0x8006F2C4  file 0x5FAC4  span 0xD8 bytes / 54 words
 * evidence: docs/evidence/func_8006F2C4/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8006F2C4.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_800942E4 PE_DECOMP_PTRGLOBAL(0x800942E4u, unsigned char)
#define D_800942E8 PE_DECOMP_PTRGLOBAL(0x800942E8u, unsigned char)
#define D_800E10A0 PE_DECOMP_ARRAY(0x800E10A0u, int)
#undef D_800B0CD8
#define D_800B0CD8 PE_DECOMP_SCALAR(0x800B0CD8u, unsigned int)

/* ── verbatim matching leaf (src/func_8006F2C4.c) ───────────────────────── */

/*
 * func_8006F2C4 — id-arena record reset.
 * VRAM 0x8006F2C4 / file 0x5FAC4 / size 0xD8 (54 words).
 *
 * ids 0x00..0x0A live in D_800942E4 (stride 0xA0C), 0x0B..0x15 in D_800942E8
 * (stride 0x10C). If the record's handler byte (offset 1) is 0x72, first zero
 * seven words of the D_800E10A0 voice table and clear bit 16 of the
 * D_800B0CD8 volume flags. Then bytes 0..3 become 00 FF FF FF and the words at
 * +4/+8 are zeroed. Returns 0, or -1 for an out-of-range id. Both arenas are
 * pointer globals. era -O2 -G0.
 */
/* shimmed by pe_guest_decomp.h: D_800942E4 */
/* shimmed by pe_guest_decomp.h: D_800942E8 */
/* shimmed by pe_guest_decomp.h: D_800E10A0 */
/* shimmed by pe_guest_decomp.h: D_800B0CD8 */

int func_8006F2C4(int idx)
{
    unsigned char *p;

    if ((unsigned int)idx >= 0x16)
        return -1;

    if ((unsigned int)idx >= 0xB)
        p = D_800942E8 + (idx - 0xB) * 0x10C;
    else
        p = D_800942E4 + idx * 0xA0C;

    if (p[1] == 0x72) {
        unsigned int i;
        unsigned int *flagsPtr;

        for (i = 0x6C; i < 0x73; i++)
            D_800E10A0[i - 0x6C] = 0;
        flagsPtr = &D_800B0CD8;
        *flagsPtr &= 0xFFFEFFFF;
    }

    p[0] = 0;
    p[1] = 0xFF;
    p[2] = 0xFF;
    p[3] = 0xFF;
    *(int *)(p + 4) = 0;
    *(int *)(p + 8) = 0;
    return 0;
}

