/*
 * decomp-source: func_8007FC88
 * matched VMA 0x8007FC88  file 0x70488  span 0x24 bytes / 9 words
 * evidence: docs/evidence/func_8007FC88/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8007FC88.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
int func_8007FC88(pe_addr_t pe_result)
{
    /* verbatim body (src/func_8007FC88.c) */

    return func_8007B290(1, pe_result);

}
