/*
 * decomp-source: func_800197F0
 * matched VMA 0x800197F0  file 0x9FF0  span 0x20 bytes / 8 words
 * evidence: docs/evidence/func_800197F0/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800197F0.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* ── verbatim matching leaf (src/func_800197F0.c) ───────────────────────── */

/* Phase 5EK: volume-cadence twin of func_800197D0 (era path). */
/* shimmed by pe_guest_decomp.h: func_800375C4 */

int func_800197F0(void) {
    func_800375C4();
    return 1;
}

