/*
 * decomp-source: func_8007FCAC
 * matched VMA 0x8007FCAC  file 0x704AC  span 0x10 bytes / 4 words
 * evidence: docs/evidence/func_8007FCAC/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8007FCAC.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009B590 PE_DECOMP_SCALAR(0x8009B590u, int)

/* ── verbatim matching leaf (src/func_8007FCAC.c) ───────────────────────── */

/* Phase 5BA: fiftieth matching C leaf (mid-6FF88 carve).
 * VRAM 0x8007FCAC / file 0x704AC / size 0x10.
 * Original: lui $v0,%hi(D_8009B590); lw $v0,%lo(D_8009B590)($v0);
 *           jr $ra; nop
 * 32-bit global getter; plain Phase 4J -O1 emits the exact four words.
 */
/* shimmed by pe_guest_decomp.h: D_8009B590 */

int func_8007FCAC(void) {
    return D_8009B590;
}

