/*
 * decomp-source: func_8006599C
 * matched VMA 0x8006599C  file 0x5619C  span 0x2C bytes / 11 words
 * evidence: docs/evidence/func_8006599C/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8006599C.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_800B1624 PE_DECOMP_PTRGLOBAL(0x800B1624u, unsigned char *volatile)

/* ── verbatim matching leaf (src/func_8006599C.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: D_800B1624 */
short func_8006599C(int a0){return *(short *)(D_800B1624 + *(int *)(D_800B1624 + 0x10) + (a0 << 4) + 6);}

