/*
 * decomp-source: func_800D4850
 * matched VMA 0x800D4850  file 0xC5050  span 0x10 bytes / 4 words
 * evidence: docs/evidence/func_800D4850/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800D4850.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
int func_800D4850(pe_addr_t pe_arg0)
{
    unsigned char *host_arg0 = (unsigned char *)PE_Translate(pe_arg0, 1);
    /* verbatim body (src/func_800D4850.c) */

    *host_arg0 = 4;
    return 0;

}
