/*
 * decomp-source: func_80050BE8
 * matched VMA 0x80050BE8  file 0x413E8  span 0x20 bytes / 8 words
 * evidence: docs/evidence/func_80050BE8/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80050BE8.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* boundary: func_80057F14 has no pc_port implementation yet */
#define func_80057F14(...) PE_D_COMP_BOUNDARY0("func_80057F14", 0x80057F14u)


/* ── verbatim matching leaf (src/func_80050BE8.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: func_80057F14 */

void func_80050BE8(void) {
    func_80057F14();
}

