/*
 * decomp-source: func_8003FFAC
 * matched VMA 0x8003FFAC  file 0x307AC  span 0x10 bytes / 4 words
 * evidence: docs/evidence/func_8003FFAC/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8003FFAC.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_800A1704 PE_DECOMP_SCALAR(0x800A1704u, int)

/* ── verbatim matching leaf (src/func_8003FFAC.c) ───────────────────────── */

/* Phase 5EE: era $at absolute-sw pilot.
 * VRAM 0x8003FFAC / file 0x307AC / size 0x10.
 * The matching getter func_8003FFBC already declares this global as int.
 */
/* shimmed by pe_guest_decomp.h: D_800A1704 */

void func_8003FFAC(int value) {
    D_800A1704 = value;
}

