/*
 * decomp-source: func_800865A4
 * matched VMA 0x800865A4  file 0x76DA4  span 0x64 bytes / 25 words
 * evidence: docs/evidence/func_800865A4/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800865A4.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_800BCD80 PE_DECOMP_SCALAR(0x800BCD80u, int)
#define D_800BCD84 PE_DECOMP_SCALAR(0x800BCD84u, int)
#define D_800BCD88 PE_DECOMP_SCALAR(0x800BCD88u, int)
#define D_800BCD8C PE_DECOMP_SCALAR(0x800BCD8Cu, int)
#define D_800BCD90 PE_DECOMP_SCALAR(0x800BCD90u, int)

/* ── verbatim matching leaf (src/func_800865A4.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: D_800BCD80, (pe_addr_t)0x800BCD84u, D_800BCD88, (pe_addr_t)0x800BCD8Cu, D_800BCD90 */
/* shimmed by pe_guest_decomp.h: func_8008CBA8 */
void func_800865A4(int a0, int a1, int a2, int a3) { D_800BCD80=0x20; D_800BCD84=a0&0x3FF; D_800BCD88=a1&0xFFFFFF; D_800BCD8C=a2&0xFF; D_800BCD90=a3&0x7F; func_8008CBA8(); }

