/*
 * decomp-source: func_80090054
 * matched VMA 0x80090054  file 0x80854  span 0x24 bytes / 9 words
 * evidence: docs/evidence/func_80090054/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80090054.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
void func_80090054(pe_addr_t pe_a0)
{
    unsigned char *host_a0 = (unsigned char *)PE_Translate(pe_a0, 1);
    /* verbatim body (src/func_80090054.c) */

    *(unsigned int *)(host_a0 + 0x38) &= ~2;
    *(unsigned int *)(host_a0 + 0xF4) |= 3;
    *(unsigned short *)(host_a0 + 0xEA) = 0;

}
