/*
 * decomp-source: func_800906E4
 * matched VMA 0x800906E4  file 0x80EE4  span 0x38 bytes / 14 words
 * evidence: docs/evidence/func_800906E4/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800906E4.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
void func_800906E4(pe_addr_t pe_a0)
{
    unsigned char *host_D_800B290C = PE_DECOMP_PTRGLOBAL(0x800B290Cu, unsigned char);
    unsigned char *host_a0 = (unsigned char *)PE_Translate(pe_a0, 1);
    /* verbatim body (src/func_800906E4.c) */

    unsigned int v = *(unsigned int *)(host_a0 + 0x38);
    unsigned char byte;
    unsigned int f;
    v &= ~0x200u;
    *(unsigned int *)(host_a0 + 0x38) = v;
    byte = host_D_800B290C[*(unsigned short *)(host_a0 + 0x5A) << 6];
    f = *(unsigned int *)(host_a0 + 0xF4) | 0x4400;
    *(unsigned int *)(host_a0 + 0xF4) = f;
    *(unsigned short *)(host_a0 + 0x116) = byte;

}
