/*
 * decomp-source: func_8007E0C0
 * matched VMA 0x8007E0C0  file 0x6E8C0  span 0x38 bytes / 14 words
 * evidence: docs/evidence/func_8007E0C0/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8007E0C0.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_800A34B0 PE_DECOMP_ARRAY(0x800A34B0u, char)

/* boundary: func_8007E1F4 has no pc_port implementation yet */
#define func_8007E1F4(...) PE_D_COMP_BOUNDARY2("func_8007E1F4", 0x8007E1F4u, __VA_ARGS__)


/* ── verbatim matching leaf (src/func_8007E0C0.c) ───────────────────────── */

/*
 * decomp-continue-4 — func_8007E0C0, file 0x6E8C0, size 0x38.
 * Critical section around func_8007E1F4(1, D_800A34B0); returns 1.
 * Matching authority: scripts/build_us.sh EXACT SHA-1
 * 452fb033f2eaa4b18aa20a5bca60b8125af3a37b.
 */
/* shimmed by pe_guest_decomp.h: func_80072714 */
/* shimmed by pe_guest_decomp.h: func_8007E1F4 */
/* shimmed by pe_guest_decomp.h: func_80072724 */
/* shimmed by pe_guest_decomp.h: D_800A34B0 */
int func_8007E0C0(void) {
    func_80072714();
    func_8007E1F4(1, (pe_addr_t)0x800A34B0u);
    func_80072724();
    return 1;
}

