/*
 * decomp-source: func_8007A3EC
 * matched VMA 0x8007A3EC  file 0x6ABEC  span 0x14 bytes / 5 words
 * evidence: docs/evidence/func_8007A3EC/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8007A3EC.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009AFC0 PE_DECOMP_SCALAR(0x8009AFC0u, int)

/* ── verbatim matching leaf (src/func_8007A3EC.c) ───────────────────────── */

/* Phase 5EF: signed state/count exchange.
 * Type provenance: YAML-live readers use blez and slti on D_8009AFC0. */
/* shimmed by pe_guest_decomp.h: D_8009AFC0 */

int func_8007A3EC(int value) {
    int old = D_8009AFC0;
    D_8009AFC0 = value;
    return old;
}

