/*
 * decomp-source: func_80057ECC
 * matched VMA 0x80057ECC  file 0x486CC  span 0xC bytes / 3 words
 * evidence: docs/evidence/func_80057ECC/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80057ECC.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009D078 PE_DECOMP_SCALAR(0x8009D078u, int)

/* ── verbatim matching leaf (src/func_80057ECC.c) ───────────────────────── */

/* Phase 5DC: gp-relative leaf func_80057ECC.
 * VRAM 0x80057ECC / gp+0x308 -> D_8009D078. gp base 0x8009CD70.
 * -G 8 emits R_MIPS_GPREL16; _gp+abs sym resolve to retail offset. */
/* shimmed by pe_guest_decomp.h: D_8009D078 */
int func_80057ECC(void){ return D_8009D078; }

