/*
 * decomp-source: func_80082514
 * matched VMA 0x80082514  file 0x72D14  span 0x20 bytes / 8 words
 * evidence: docs/evidence/func_80082514/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80082514.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* ── verbatim matching leaf (src/func_80082514.c) ───────────────────────── */

void func_80082CDC(void);

void func_80082514(void) {
    func_80082CDC();
}

