/*
 * decomp-source: func_80080AE4
 * matched VMA 0x80080AE4  file 0x712E4  span 0x20 bytes / 8 words
 * evidence: docs/evidence/func_80080AE4/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80080AE4.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
/* boundary: func_8007BF44 has no pc_port implementation yet */
#define func_8007BF44(...) PE_D_COMP_BOUNDARY2("func_8007BF44", 0x8007BF44u, __VA_ARGS__)

int func_80080AE4(pe_addr_t pe_buffer, int value)
{
    /* verbatim body (src/func_80080AE4.c) */

    return func_8007BF44( pe_buffer, value) == 0;

}
