/*
 * decomp-source: func_8008F178
 * matched VMA 0x8008F178  file 0x7F978  span 0x38 bytes / 14 words
 * evidence: docs/evidence/func_8008F178/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8008F178.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_800B2900 PE_DECOMP_SCALAR(0x800B2900u, char)

/* boundary: func_8008F0D0 has no pc_port implementation yet */
#define func_8008F0D0(...) PE_D_COMP_BOUNDARY3("func_8008F0D0", 0x8008F0D0u, __VA_ARGS__)


/* ── verbatim matching leaf (src/func_8008F178.c) ───────────────────────── */

/* VRAM 0x8008F178 / file 0x7F978 / size 0x38. */
/* shimmed by pe_guest_decomp.h: D_800B2900 */
/* shimmed by pe_guest_decomp.h: func_8008F0D0 */
void func_8008F178(int arg0, int arg1) {
    int *p;
    *(short *)(arg0 + 0x5A) = arg1;
    p = (int *)((char *)&D_800B2900 + (arg1 << 6));
    func_8008F0D0(arg0, p, *p);
}

