/*
 * decomp-source: func_80075C6C
 * matched VMA 0x80075C6C  file 0x6646C  span 0x28 bytes / 10 words
 * evidence: docs/evidence/func_80075C6C/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80075C6C.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
void func_80075C6C(pe_addr_t pe_a0, int a1)
{
    unsigned char *host_a0 = (unsigned char *)PE_Translate(pe_a0, 1);
    /* verbatim body (src/func_80075C6C.c) */

    host_a0[3] = 2;
    *(int *)(host_a0 + 4) = a1 ? 0xE6000001 : 0xE6000000;
    *(int *)(host_a0 + 8) = 0;

}
