/*
 * decomp-source: func_800835B0
 * matched VMA 0x800835B0  file 0x73DB0  span 0x10 bytes / 4 words
 * evidence: docs/evidence/func_800835B0/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800835B0.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
void func_800835B0(pe_addr_t pe_arg0, unsigned char arg1, unsigned int arg2, unsigned char arg3)
{
    unsigned char *host_arg0 = (unsigned char *)PE_Translate(pe_arg0, 1);
    /* verbatim body (src/func_800835B0.c) */

    host_arg0[0x36] = arg1;
    *(unsigned int *)(host_arg0 + 0x2C) = arg2;
    host_arg0[0x35] = arg3;

}
