/*
 * decomp-source: func_80050020
 * matched VMA 0x80050020  file 0x40820  span 0x18 bytes / 6 words
 * evidence: docs/evidence/func_80050020/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80050020.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_800A1888 PE_DECOMP_ARRAY(0x800A1888u, unsigned int)

/* ── verbatim matching leaf (src/func_80050020.c) ───────────────────────── */

/* VRAM 0x80050020 / file 0x40820 / size 0x18. */
/* shimmed by pe_guest_decomp.h: D_800A1888 */

unsigned int func_80050020(unsigned int index) {
    return D_800A1888[index];
}

