/*
 * decomp-source: func_8007DD74
 * matched VMA 0x8007DD74  file 0x6E574  span 0x34 bytes / 13 words
 * evidence: docs/evidence/func_8007DD74/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8007DD74.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* boundary: func_8007DDC4 has no pc_port implementation yet */
#define func_8007DDC4(...) PE_D_COMP_BOUNDARY1("func_8007DDC4", 0x8007DDC4u, __VA_ARGS__)

/* boundary: func_8007DDB4 has no pc_port implementation yet */
#define func_8007DDB4(...) PE_D_COMP_BOUNDARY3("func_8007DDB4", 0x8007DDB4u, __VA_ARGS__)


/* ── verbatim matching leaf (src/func_8007DD74.c) ───────────────────────── */

/* VRAM 0x8007DD74 / file 0x6E574 / size 0x34.
 * Two-call forwarding wrapper (a0, then a0/0x3F/0); era -O2 -G0 with the
 * epilogue stack restore filled into the `jr $ra` delay slot. */
/* shimmed by pe_guest_decomp.h: func_8007DDC4 */
/* shimmed by pe_guest_decomp.h: func_8007DDB4 */

void func_8007DD74(int arg0) {
    func_8007DDC4(arg0);
    func_8007DDB4(arg0, 0x3F, 0);
}

