/*
 * decomp-source: func_8003DFD0
 * matched VMA 0x8003DFD0  file 0x2E7D0  span 0x8 bytes / 2 words
 * evidence: docs/evidence/func_8003DFD0/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8003DFD0.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* ── verbatim matching leaf (src/func_8003DFD0.c) ───────────────────────── */

/* Phase 5EA: FIRST era-compiler leaf func_8003DFD0. Return-0; retail uses
 * addu $v0,$zero,$zero (Psy-Q move->addu), which GCC 14.2 renders as or.
 * Compiled via era GCC 2.7.2-psx + maspsx (era_compile, -O2 -G0). */
int func_8003DFD0(void){ return 0; }

