/*
 * decomp-source: func_80076C10
 * matched VMA 0x80076C10  file 0x67410  span 0x24 bytes / 9 words
 * evidence: docs/evidence/func_80076C10/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80076C10.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* ── verbatim matching leaf (src/func_80076C10.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: func_80076C34 */

void func_80076C10(int arg0, int arg1, int arg2) {
    func_80076C34(arg0, arg1, 0, arg2);
}

