/*
 * decomp-source: func_800822AC
 * matched VMA 0x800822AC  file 0x72AAC  span 0x10 bytes / 4 words
 * evidence: docs/evidence/func_800822AC/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800822AC.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009B70C PE_DECOMP_SCALAR(0x8009B70Cu, int)

/* ── verbatim matching leaf (src/func_800822AC.c) ───────────────────────── */

/* Phase 5BC: fifty-second matching C leaf (mid-71150 carve).
 * VRAM 0x800822AC / file 0x72AAC / size 0x10.
 * Original: lui $v0,%hi(D_8009B70C); lw $v0,%lo(D_8009B70C)($v0);
 *           jr $ra; nop
 * 32-bit global getter; plain Phase 4J -O1 emits the exact four words.
 */
/* shimmed by pe_guest_decomp.h: D_8009B70C */

int func_800822AC(void) {
    return D_8009B70C;
}

