/*
 * decomp-source: func_80077C24
 * matched VMA 0x80077C24  file 0x68424  span 0x14 bytes / 5 words
 * evidence: docs/evidence/func_80077C24/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80077C24.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
void func_80077C24(pe_addr_t pe_arg0)
{
    unsigned char *host_arg0 = (unsigned char *)PE_Translate(pe_arg0, 1);
    /* verbatim body (src/func_80077C24.c) */

    host_arg0[3] = 2;
    host_arg0[7] = 104;

}
