/*
 * decomp-source: func_8007DEB0
 * matched VMA 0x8007DEB0  file 0x6E6B0  span 0x10 bytes / 4 words
 * evidence: docs/evidence/func_8007DEB0/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8007DEB0.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009B4AC PE_DECOMP_SCALAR(0x8009B4ACu, int)

/* ── verbatim matching leaf (src/func_8007DEB0.c) ───────────────────────── */

/* Phase 5AY: forty-eighth matching C leaf (mid-65238 carve).
 * VRAM 0x8007DEB0 / file 0x6E6B0 / size 0x10.
 * Original: lui $v0,%hi(D_8009B4AC); lw $v0,%lo(D_8009B4AC)($v0);
 *           jr $ra; nop
 * 32-bit global getter; plain Phase 4J -O1 emits the exact four words.
 */
/* shimmed by pe_guest_decomp.h: D_8009B4AC */

int func_8007DEB0(void) {
    return D_8009B4AC;
}

