/*
 * decomp-source: func_80042964
 * matched VMA 0x80042964  file 0x33164  span 0x28 bytes / 10 words
 * evidence: docs/evidence/func_80042964/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80042964.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_800A0EDE PE_DECOMP_ARRAY(0x800A0EDEu, unsigned char)

/* ── verbatim matching leaf (src/func_80042964.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: D_800A0EDE */

int func_80042964(int a0) {
    return D_800A0EDE[a0 * 1048];
}

