/*
 * decomp-source: func_80080930
 * matched VMA 0x80080930  file 0x71130  span 0x10 bytes / 4 words
 * evidence: docs/evidence/func_80080930/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80080930.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009B554 PE_DECOMP_SCALAR(0x8009B554u, unsigned int)

/* ── verbatim matching leaf (src/func_80080930.c) ───────────────────────── */

/* Phase 5EF: set opaque word D_8009B554 to one.
 * Readers are branch-only; refine if a narrowing reader is found. */
/* shimmed by pe_guest_decomp.h: D_8009B554 */

void func_80080930(void) {
    D_8009B554 = 1;
}

