/*
 * decomp-source: func_8007A8CC
 * matched VMA 0x8007A8CC  file 0x6B0CC  span 0x20 bytes / 8 words
 * evidence: docs/evidence/func_8007A8CC/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8007A8CC.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* boundary: func_8007C044 has no pc_port implementation yet */
#define func_8007C044(...) PE_D_COMP_BOUNDARY0("func_8007C044", 0x8007C044u)


/* ── verbatim matching leaf (src/func_8007A8CC.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: func_8007C044 */

int func_8007A8CC(void) {
    return !func_8007C044();
}

