/*
 * decomp-source: func_800858E8
 * matched VMA 0x800858E8  file 0x760E8  span 0x30 bytes / 12 words
 * evidence: docs/evidence/func_800858E8/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800858E8.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009B7CC PE_DECOMP_PTRGLOBAL(0x8009B7CCu, unsigned int)
#define D_8009B7D4 PE_DECOMP_ARRAY(0x8009B7D4u, unsigned int)

/* ── verbatim matching leaf (src/func_800858E8.c) ───────────────────────── */

/* VRAM 0x800858E8 / file 0x760E8 / size 0x30.
 * OR the indexed word into D_8009B7CC[1]; return idx < 3. */
/* shimmed by pe_guest_decomp.h: D_8009B7CC */
/* shimmed by pe_guest_decomp.h: D_8009B7D4 */
int func_800858E8(int a0) {
    int idx = a0 & 0xFFFF;
    D_8009B7CC[1] |= D_8009B7D4[idx];
    return idx < 3;
}

