/*
 * decomp-source: func_800504BC
 * matched VMA 0x800504BC  file 0x40CBC  span 0x38 bytes / 14 words
 * evidence: docs/evidence/func_800504BC/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800504BC.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* ── verbatim matching leaf (src/func_800504BC.c) ───────────────────────── */

/*
 * decomp-continue-4 — func_800504BC, file 0x40CBC, size 0x38.
 * func_8005E8A4(0,1) then func_80064C54(a0 + 0x33).
 * Matching authority: scripts/build_us.sh EXACT SHA-1
 * 452fb033f2eaa4b18aa20a5bca60b8125af3a37b.
 */
/* shimmed by pe_guest_decomp.h: func_8005E8A4 */
/* shimmed by pe_guest_decomp.h: func_80064C54 */
void func_800504BC(int a0) {
    func_8005E8A4(0, 1);
    func_80064C54(a0 + 0x33);
}

