/*
 * decomp-source: func_800197D0
 * matched VMA 0x800197D0  file 0x9FD0  span 0x20 bytes / 8 words
 * evidence: docs/evidence/func_800197D0/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800197D0.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* ── verbatim matching leaf (src/func_800197D0.c) ───────────────────────── */

/* Phase 5EI-first-nonleaf: first non-leaf probe func_800197D0 (era path).
 * VRAM 0x800197D0 / file 0x9FD0 / size 0x20.
 * Frame + jal only: callee func_800375B4 is void(void), zero args — no arg setup.
 * era -O2 -G8 (standing int-return rule; mirrors the 5EH entry).
 * ROM: addiu $sp,-0x18; sw $ra,0x10($sp); jal func_800375B4; nop;
 *      lw $ra,0x10($sp); addiu $v0,1; jr $ra; addiu $sp,+0x18 (jr delay slot). */
/* shimmed by pe_guest_decomp.h: func_800375B4 */
int func_800197D0(void) {
    func_800375B4();
    return 1;
}

