/*
 * decomp-source: func_80043038
 * matched VMA 0x80043038  file 0x33838  span 0x14 bytes / 5 words
 * evidence: docs/evidence/func_80043038/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80043038.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009CED8 PE_DECOMP_SCALAR(0x8009CED8u, int)

/* ── verbatim matching leaf (src/func_80043038.c) ───────────────────────── */

/* Phase 5DG: complex gp one-off func_80043038 (-G 8). */
/* shimmed by pe_guest_decomp.h: D_8009CED8 */
int func_80043038(void){ return D_8009CED8 == 7; }

