/*
 * decomp-source: func_80050088
 * matched VMA 0x80050088  file 0x40888  span 0x20 bytes / 8 words
 * evidence: docs/evidence/func_80050088/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80050088.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
void func_80050088(pe_addr_t pe_object)
{
    /* verbatim body (src/func_80050088.c) */

    func_800638D8( pe_object, 0);

}
