/*
 * decomp-source: func_800CA700
 * matched VMA 0x800CA700  file 0xBAF00  span 0x28 bytes / 10 words
 * evidence: docs/evidence/func_800CA700/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800CA700.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_800E0B84 PE_DECOMP_ARRAY(0x800E0B84u, unsigned char)

/* ── verbatim matching leaf (src/func_800CA700.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: func_800C2414 */

/* shimmed by pe_guest_decomp.h: D_800E0B84 */

int func_800CA700(int arg0) {
    func_800C2414(arg0, (pe_addr_t)0x800E0B84u);
    return 0;
}

