/*
 * decomp-source: func_800CD5A4
 * matched VMA 0x800CD5A4  file 0xBDDA4  span 0xC bytes / 3 words
 * evidence: docs/evidence/func_800CD5A4/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800CD5A4.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
void func_800CD5A4(unsigned int arg0, pe_addr_t pe_arg1)
{
    unsigned char *host_arg1 = (unsigned char *)PE_Translate(pe_arg1, 1);
    /* verbatim body (src/func_800CD5A4.c) */

    host_arg1[1] = 2;

}
