/*
 * decomp-source: func_80082CDC
 * matched VMA 0x80082CDC  file 0x734DC  span 0x14 bytes / 5 words
 * evidence: docs/evidence/func_80082CDC/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80082CDC.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009B78C PE_DECOMP_SCALAR(0x8009B78Cu, int)

/* ── verbatim matching leaf (src/func_80082CDC.c) ───────────────────────── */

/* Phase 5EF: return and clear the D_8009B78C int state flag.
 * Type provenance: YAML-live writer stores state value one. */
/* shimmed by pe_guest_decomp.h: D_8009B78C */

int func_80082CDC(void) {
    int old = D_8009B78C;
    D_8009B78C = 0;
    return old;
}

