/*
 * decomp-source: func_80019260
 * matched VMA 0x80019260  file 0x9A60  span 0x38 bytes / 14 words
 * evidence: docs/evidence/func_80019260/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80019260.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009D2F0 PE_DECOMP_PTRGLOBAL(0x8009D2F0u, unsigned char)

/* boundary: func_8003E0D0 has no pc_port implementation yet */
#define func_8003E0D0(...) PE_D_COMP_BOUNDARY1("func_8003E0D0", 0x8003E0D0u, __VA_ARGS__)


/* ── verbatim matching leaf (src/func_80019260.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: D_8009D2F0 */
/* shimmed by pe_guest_decomp.h: func_8003E0D0 */
int func_80019260(void) {
    func_8003E0D0(D_8009D2F0 + 0x1B4);
    *(unsigned int *)(D_8009D2F0 + 0x18C) = 0;
    return 1;
}

