/*
 * decomp-source: func_8005E54C
 * matched VMA 0x8005E54C  file 0x4ED4C  span 0x30 bytes / 12 words
 * evidence: docs/evidence/func_8005E54C/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8005E54C.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009D0E8 PE_DECOMP_SCALAR(0x8009D0E8u, int)

/* ── verbatim matching leaf (src/func_8005E54C.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: D_8009D0E8 */

/* shimmed by pe_guest_decomp.h: func_8005E038 */

int func_8005E54C(void) {
    if (D_8009D0E8 != 0) {
        return func_8005E038();
    }
    return 0;
}

