/*
 * decomp-source: func_800C9EA0
 * matched VMA 0x800C9EA0  file 0xBA6A0  span 0x8 bytes / 2 words
 * evidence: docs/evidence/func_800C9EA0/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800C9EA0.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* ── verbatim matching leaf (src/func_800C9EA0.c) ───────────────────────── */

/* Phase 5V: nineteenth matching C leaf (third mid-tail carve, from B9A68.s).
 * VRAM 0x800C9EA0 / file 0xBA6A0 / size 0x8.
 * Original: jr $ra; nop — empty return stub.
 * Scratch probe: GCC 14.2 Phase 4J flags exact 0x8-byte match.
 */
void func_800C9EA0(void) {
}

