/*
 * decomp-source: func_800CBFBC
 * matched VMA 0x800CBFBC  file 0xBC7BC  span 0x8 bytes / 2 words
 * evidence: docs/evidence/func_800CBFBC/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800CBFBC.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* ── verbatim matching leaf (src/func_800CBFBC.c) ───────────────────────── */

int func_800CBFBC(void) {
    return 0;
}

