/*
 * decomp-source: func_8004C5DC
 * matched VMA 0x8004C5DC  file 0x3CDDC  span 0x2C bytes / 11 words
 * evidence: docs/evidence/func_8004C5DC/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8004C5DC.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* ── verbatim matching leaf (src/func_8004C5DC.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: func_80062A34 */
/* shimmed by pe_guest_decomp.h: func_80062F1C */

void func_8004C5DC(void) {
    func_80062F1C(func_80062A34(1, 19));
}

