/*
 * decomp-source: func_80075C04
 * matched VMA 0x80075C04  file 0x66404  span 0x40 bytes / 16 words
 * evidence: docs/evidence/func_80075C04/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80075C04.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
int func_80075C04(pe_addr_t pe_arg0, pe_addr_t pe_arg1)
{
    char *host_arg0 = (char *)PE_Translate(pe_arg0, 1);
    short *host_arg1 = (short *)PE_Translate(pe_arg1, 1);
    /* verbatim body (src/func_80075C04.c) */

    int v;

    host_arg0[3] = 2;
    v = func_800762A0(host_arg1[0], host_arg1[1]);
    *(int *)(host_arg0 + 4) = v;
    *(int *)(host_arg0 + 8) = 0;
    return v;

}
