/*
 * decomp-source: func_8007E594
 * matched VMA 0x8007E594  file 0x6ED94  span 0x30 bytes / 12 words
 * evidence: docs/evidence/func_8007E594/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8007E594.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
void func_8007E594(pe_addr_t pe_a0)
{
    unsigned char *host_a0 = (unsigned char *)PE_Translate(pe_a0, 1);
    /* verbatim body (src/func_8007E594.c) */

    int i;
    unsigned char *q;

    *(unsigned int *)host_a0 = 0;
    host_a0[4] = 0;
    i = 3;
    q = host_a0 + 3;
    do {
        q[5] = 0;
        i--;
        q--;
    } while (i >= 0);
    *(unsigned int *)(host_a0 + 0xC) = 0;
    *(unsigned int *)(host_a0 + 0x10) = 0;
    *(unsigned int *)(host_a0 + 0x14) = 0;

}
