/*
 * decomp-source: func_80076B44
 * matched VMA 0x80076B44  file 0x67344  span 0x14 bytes / 5 words
 * evidence: docs/evidence/func_80076B44/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80076B44.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_800A3348 PE_DECOMP_ARRAY(0x800A3348u, unsigned char)

/* ── verbatim matching leaf (src/func_80076B44.c) ───────────────────────── */

/* VRAM 0x80076B44 / file 0x67344 / size 0x14.
 * Byte-table getter: D_800A3348[a0] with no index scaling. */
/* shimmed by pe_guest_decomp.h: D_800A3348 */

unsigned char func_80076B44(int index) {
    return D_800A3348[index];
}

