/*
 * decomp-source: func_8008E7F4
 * matched VMA 0x8008E7F4  file 0x7EFF4  span 0x4C bytes / 19 words
 * evidence: docs/evidence/func_8008E7F4/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8008E7F4.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
/* boundary: func_8008E4E8 has no pc_port implementation yet */
#define func_8008E4E8(...) PE_D_COMP_BOUNDARY2("func_8008E4E8", 0x8008E4E8u, __VA_ARGS__)
/* boundary: func_8008E664 has no pc_port implementation yet */
#define func_8008E664(...) PE_D_COMP_BOUNDARY2("func_8008E664", 0x8008E664u, __VA_ARGS__)

void func_8008E7F4(pe_addr_t pe_a0, int a1)
{
    unsigned char *host_a0 = (unsigned char *)PE_Translate(pe_a0, 1);
    /* verbatim body (src/func_8008E7F4.c) */

    int v = *(short *)(host_a0 + 0xE2);
    if ((unsigned)v < (unsigned)a1) func_8008E4E8( pe_a0, a1);
    else if ((unsigned)a1 < (unsigned)v) func_8008E664( pe_a0, a1);

}
