/*
 * decomp-source: func_80064A48
 * matched VMA 0x80064A48  file 0x55248  span 0xC bytes / 3 words
 * evidence: docs/evidence/func_80064A48/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80064A48.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009D16C PE_DECOMP_SCALAR(0x8009D16Cu, int)

/* ── verbatim matching leaf (src/func_80064A48.c) ───────────────────────── */

/* Phase 5DC: gp-relative leaf func_80064A48.
 * VRAM 0x80064A48 / gp+0x3FC -> D_8009D16C. gp base 0x8009CD70.
 * -G 8 emits R_MIPS_GPREL16; _gp+abs sym resolve to retail offset. */
/* shimmed by pe_guest_decomp.h: D_8009D16C */
int func_80064A48(void){ return D_8009D16C; }

