/*
 * decomp-source: func_8005E894
 * matched VMA 0x8005E894  file 0x4F094  span 0x10 bytes / 4 words
 * evidence: docs/evidence/func_8005E894/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8005E894.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009D124 PE_DECOMP_SCALAR(0x8009D124u, int)
#define D_8009D128 PE_DECOMP_SCALAR(0x8009D128u, int)

/* ── verbatim matching leaf (src/func_8005E894.c) ───────────────────────── */

/* Phase 5DD: gp-relative setter func_8005E894 (-G 8 -fno-delayed-branch).
 * gp base 0x8009CD70; R_MIPS_GPREL16 + _gp resolve to retail offset. */
/* shimmed by pe_guest_decomp.h: D_8009D124, D_8009D128 */
void func_8005E894(int a0, int a1){ D_8009D124 = a0; D_8009D128 = a1; }

