/*
 * decomp-source: func_80083C20
 * matched VMA 0x80083C20  file 0x74420  span 0x1C bytes / 7 words
 * evidence: docs/evidence/func_80083C20/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80083C20.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
void func_80083C20(pe_addr_t pe_a0)
{
    unsigned char *host_a0 = (unsigned char *)PE_Translate(pe_a0, 1);
    /* verbatim body (src/func_80083C20.c) */

    unsigned int value = *(unsigned int *)(host_a0 + 0x20);
    host_a0[0x36] = 0x4D;
    host_a0[0x35] = 6;
    *(unsigned int *)(host_a0 + 0x2C) = value;

}
