/*
 * decomp-source: func_80038D0C
 * matched VMA 0x80038D0C  file 0x2950C  span 0x10 bytes / 4 words
 * evidence: docs/evidence/func_80038D0C/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80038D0C.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_80091A1C PE_DECOMP_SCALAR(0x80091A1Cu, unsigned char)

/* ── verbatim matching leaf (src/func_80038D0C.c) ───────────────────────── */

/* Phase 5BQ: sixty-sixth matching C leaf (mid-98BC carve).
 * VRAM 0x80038D0C / file 0x2950C / size 0x10.
 * Original: lui $v0,%hi(D_80091A1C); lbu $v0,%lo(D_80091A1C)($v0);
 *           jr $ra; sltu $v0,$zero,$v0
 */
/* shimmed by pe_guest_decomp.h: D_80091A1C */

int func_80038D0C(void) {
    return D_80091A1C != 0;
}

