/*
 * decomp-source: func_800869AC
 * matched VMA 0x800869AC  file 0x771AC  span 0x38 bytes / 14 words
 * evidence: docs/evidence/func_800869AC/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800869AC.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_800BCD80 PE_DECOMP_SCALAR(0x800BCD80u, int)
#define D_800BCD84 PE_DECOMP_SCALAR(0x800BCD84u, int)

/* ── verbatim matching leaf (src/func_800869AC.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: D_800BCD80, D_800BCD84 */
/* shimmed by pe_guest_decomp.h: func_8008CBA8 */
void func_800869AC(int a0) { D_800BCD80 = 0xAA; D_800BCD84 = a0 & 0xFF; func_8008CBA8(); }

