/*
 * decomp-source: func_800867B0
 * matched VMA 0x800867B0  file 0x76FB0  span 0x34 bytes / 13 words
 * evidence: docs/evidence/func_800867B0/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800867B0.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_800BCD80 PE_DECOMP_SCALAR(0x800BCD80u, int)
#define D_800BCD84 PE_DECOMP_SCALAR(0x800BCD84u, int)

/* ── verbatim matching leaf (src/func_800867B0.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: D_800BCD80, D_800BCD84 */
/* shimmed by pe_guest_decomp.h: func_8008CBA8 */
void func_800867B0(int a0) { D_800BCD80 = 0x92; D_800BCD84 = a0; func_8008CBA8(); }

