/*
 * decomp-source: func_800CA7A8
 * matched VMA 0x800CA7A8  file 0xBAFA8  span 0x8 bytes / 2 words
 * evidence: docs/evidence/func_800CA7A8/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800CA7A8.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* ── verbatim matching leaf (src/func_800CA7A8.c) ───────────────────────── */

int func_800CA7A8(void) {
    return 0;
}

