/*
 * decomp-source: func_80085918
 * matched VMA 0x80085918  file 0x76118  span 0x34 bytes / 13 words
 * evidence: docs/evidence/func_80085918/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80085918.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009B7CC PE_DECOMP_PTRGLOBAL(0x8009B7CCu, unsigned int)
#define D_8009B7D4 PE_DECOMP_ARRAY(0x8009B7D4u, unsigned int)

/* ── verbatim matching leaf (src/func_80085918.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: D_8009B7CC */
/* shimmed by pe_guest_decomp.h: D_8009B7D4 */
int func_80085918(unsigned int a0) {
    unsigned int i = a0 & 0xFFFF;
    D_8009B7CC[1] &= ~D_8009B7D4[i];
    return 1;
}

