/*
 * decomp-source: func_8007DE40
 * matched VMA 0x8007DE40  file 0x6E640  span 0x38 bytes / 14 words
 * evidence: docs/evidence/func_8007DE40/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8007DE40.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* boundary: func_8007E324 has no pc_port implementation yet */
#define func_8007E324(...) PE_D_COMP_BOUNDARY0("func_8007E324", 0x8007E324u)


/* ── verbatim matching leaf (src/func_8007DE40.c) ───────────────────────── */

/*
 * decomp-continue-4 — func_8007DE40, file 0x6E640, size 0x38.
 * EnterCriticalSection / func_8007E324 / func_80073C74(0) / ExitCriticalSection.
 * Matching authority: scripts/build_us.sh EXACT SHA-1
 * 452fb033f2eaa4b18aa20a5bca60b8125af3a37b.
 */
/* shimmed by pe_guest_decomp.h: func_80072714 */
/* shimmed by pe_guest_decomp.h: func_8007E324 */
/* shimmed by pe_guest_decomp.h: func_80073C74 */
/* shimmed by pe_guest_decomp.h: func_80072724 */
void func_8007DE40(void) {
    func_80072714();
    func_8007E324();
    func_80073C74(0);
    func_80072724();
}

