/*
 * decomp-source: func_8007A400
 * matched VMA 0x8007A400  file 0x6AC00  span 0x34 bytes / 13 words
 * evidence: docs/evidence/func_8007A400/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8007A400.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_800119CC PE_DECOMP_ARRAY(0x800119CCu, unsigned char)
#define D_8009AFDC PE_DECOMP_ARRAY(0x8009AFDCu, unsigned char *)

/* ── verbatim matching leaf (src/func_8007A400.c) ───────────────────────── */

/* VRAM 0x8007A400 / file 0x6AC00 / size 0x34.
 * Pointer-table lookup with 0x1C bound; fallback is the D_800119CC string. */
/* shimmed by pe_guest_decomp.h: D_8009AFDC */
/* shimmed by pe_guest_decomp.h: D_800119CC */

unsigned char *func_8007A400(unsigned int index) {
    index &= 0xFF;
    if (index >= 0x1C)
        return D_800119CC;
    return D_8009AFDC[index];
}

