/*
 * decomp-source: func_80074CB8
 * matched VMA 0x80074CB8  file 0x654B8  span 0x10 bytes / 4 words
 * evidence: docs/evidence/func_80074CB8/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80074CB8.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009574E PE_DECOMP_SCALAR(0x8009574Eu, unsigned char)

/* ── verbatim matching leaf (src/func_80074CB8.c) ───────────────────────── */

/* Phase 5BO: sixty-fourth matching C leaf (mid-65238 carve).
 * VRAM 0x80074CB8 / file 0x654B8 / size 0x10.
 * Original: lui $v0,%hi((pe_addr_t)0x8009574Eu); lbu $v0,%lo((pe_addr_t)0x8009574Eu)($v0);
 *           jr $ra; nop
 */
/* shimmed by pe_guest_decomp.h: D_8009574E */

unsigned char func_80074CB8(void) {
    return D_8009574E;
}

