/*
 * decomp-source: func_800C6EE8
 * matched VMA 0x800C6EE8  file 0xB76E8  span 0x10 bytes / 4 words
 * evidence: docs/evidence/func_800C6EE8/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800C6EE8.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_800F3420 PE_DECOMP_SCALAR(0x800F3420u, unsigned short)

/* ── verbatim matching leaf (src/func_800C6EE8.c) ───────────────────────── */

/* VRAM 0x800C6EE8 / file 0xB76E8 / size 0x10. */
/* shimmed by pe_guest_decomp.h: D_800F3420 */

void func_800C6EE8(unsigned int value) {
    D_800F3420 = (unsigned short)value;
}

