/*
 * decomp-source: func_8007A3CC
 * matched VMA 0x8007A3CC  file 0x6ABCC  span 0x20 bytes / 8 words
 * evidence: docs/evidence/func_8007A3CC/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8007A3CC.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* ── verbatim matching leaf (src/func_8007A3CC.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: func_8007B9EC */

void func_8007A3CC(void) {
    func_8007B9EC();
}

