/*
 * decomp-source: func_8007DBC8
 * matched VMA 0x8007DBC8  file 0x6E3C8  span 0x3C bytes / 15 words
 * evidence: docs/evidence/func_8007DBC8/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8007DBC8.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009B3FC PE_DECOMP_PTRGLOBAL(0x8009B3FCu, unsigned short)
#define D_8009B424 PE_DECOMP_SCALAR(0x8009B424u, unsigned int)

/* ── verbatim matching leaf (src/func_8007DBC8.c) ───────────────────────── */

/*
 * func_8007DBC8 — table lookup, optionally shifted by a global shift count.
 *
 * VRAM 0x8007DBC8 / file 0x6E3C8 / size 0x3C (15 words).
 * ROM: asm/disc1/6D874.s.
 *
 * Retail:
 *   unsigned short v = D_8009B3FC[a0];   // lhu a0,0(a0): value homed in $a0
 *   if (a1 == -1) return v;
 *   return v << D_8009B424;
 * The value must be a narrow `unsigned short` local so cc1 homes it in $a0
 * (`lhu a0,0(a0)` / `sllv v0,a0,v0` / `move v0,a0`); an `unsigned int` local
 * lands in $v1 and picks up a redundant `move`. D_8009B3FC is a pointer global
 * (one loaded base register), and D_8009B424 is `unsigned int` so the `sllv`
 * count is unsigned. The `-1` literal is materialised once.
 */
/* shimmed by pe_guest_decomp.h: D_8009B3FC */
/* shimmed by pe_guest_decomp.h: D_8009B424 */

int func_8007DBC8(unsigned int a0, int a1) {
    unsigned short v = D_8009B3FC[a0];

    if (a1 == -1)
        return v;
    return v << D_8009B424;
}

