/*
 * decomp-source: func_800816F4
 * matched VMA 0x800816F4  file 0x71EF4  span 0x20 bytes / 8 words
 * evidence: docs/evidence/func_800816F4/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800816F4.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
int func_800816F4(pe_addr_t pe_left, pe_addr_t pe_right)
{
    /* verbatim body (src/func_800816F4.c) */

    return func_80071A04( pe_left, pe_right, 12) == 0;

}
