/*
 * decomp-source: func_8008F694
 * matched VMA 0x8008F694  file 0x7FE94  span 0x14 bytes / 5 words
 * evidence: docs/evidence/func_8008F694/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8008F694.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
void func_8008F694(pe_addr_t pe_arg0)
{
    void *host_arg0 = (void *)PE_Translate(pe_arg0, 1);
    /* verbatim body (src/func_8008F694.c) */

    unsigned int v0;

    v0 = *(unsigned int *)host_arg0;
    v0 = v0 + 2u;
    *(unsigned int *)host_arg0 = v0;

}
