/*
 * decomp-source: func_80080D34
 * matched VMA 0x80080D34  file 0x71534  span 0x28 bytes / 10 words
 * evidence: docs/evidence/func_80080D34/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80080D34.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* ── verbatim matching leaf (src/func_80080D34.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: func_8007EE84 */

void func_80080D34(unsigned char arg0, int arg1) {
    func_8007EE84(arg0, arg1, 0, 0);
}

