/*
 * decomp-source: func_8007F7C8
 * matched VMA 0x8007F7C8  file 0x6FFC8  span 0x20 bytes / 8 words
 * evidence: docs/evidence/func_8007F7C8/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8007F7C8.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* ── verbatim matching leaf (src/func_8007F7C8.c) ───────────────────────── */

unsigned char func_8007FC08(void);

unsigned char func_8007F7C8(void) {
    return func_8007FC08();
}

