/*
 * decomp-source: func_80089F08
 * matched VMA 0x80089F08  file 0x7A708  span 0x1C bytes / 7 words
 * evidence: docs/evidence/func_80089F08/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80089F08.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
void func_80089F08(int index, pe_addr_t pe_out)
{
    unsigned char *host_D_8009B3FC = PE_DECOMP_PTRGLOBAL(0x8009B3FCu, unsigned char);
    unsigned short *host_out = (unsigned short *)PE_Translate(pe_out, 1);
    /* verbatim body (src/func_80089F08.c) */

    *host_out = *(unsigned short *)(host_D_8009B3FC + index * 16 + 0xC);

}
