/*
 * decomp-source: func_80077D30
 * matched VMA 0x80077D30  file 0x68530  span 0x90 bytes / 36 words
 * evidence: docs/evidence/func_80077D30/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80077D30.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009489C PE_DECOMP_ARRAY(0x8009489Cu, short)
#define D_8009589C PE_DECOMP_ARRAY(0x8009589Cu, short)

/* ── verbatim matching leaf (src/func_80077D30.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: D_8009489C */
/* shimmed by pe_guest_decomp.h: D_8009589C */

int func_80077D30(int a0) {
    if (a0 < 0x801) {
        if (a0 < 0x401)
            return D_8009589C[a0];
        return D_8009589C[0x800 - a0];
    }
    if (a0 < 0xC01)
        return -D_8009489C[a0];
    return -D_8009589C[0x1000 - a0];
}

