/*
 * decomp-source: func_8008D7C0
 * matched VMA 0x8008D7C0  file 0x7DFC0  span 0x10 bytes / 4 words
 * evidence: docs/evidence/func_8008D7C0/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8008D7C0.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
void func_8008D7C0(pe_addr_t pe_a0)
{
    int *host_D_8009B3A0 = &PE_DECOMP_SCALAR(0x8009B3A0u, int);
    int *host_a0 = (int *)PE_Translate(pe_a0, 1);
    /* verbatim body (src/func_8008D7C0.c) */

    *host_a0 = (*host_D_8009B3A0);

}
