/*
 * decomp-source: func_8006EBD4
 * matched VMA 0x8006EBD4  file 0x5F3D4  span 0x10 bytes / 4 words
 * evidence: docs/evidence/func_8006EBD4/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8006EBD4.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_800B0DBA PE_DECOMP_SCALAR(0x800B0DBAu, signed char)

/* ── verbatim matching leaf (src/func_8006EBD4.c) ───────────────────────── */

/* Phase 5BS: sixty-eighth matching C leaf (mid-4C4B0 carve).
 * VRAM 0x8006EBD4 / file 0x5F3D4 / size 0x10.
 * Original: lui $v0,%hi((pe_addr_t)0x800B0DBAu); lb $v0,%lo((pe_addr_t)0x800B0DBAu)($v0);
 *           jr $ra; nop
 */
/* shimmed by pe_guest_decomp.h: D_800B0DBA */

signed char func_8006EBD4(void) {
    return D_800B0DBA;
}

