/*
 * decomp-source: func_8005051C
 * matched VMA 0x8005051C  file 0x40D1C  span 0x28 bytes / 10 words
 * evidence: docs/evidence/func_8005051C/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8005051C.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009CF44 PE_DECOMP_SCALAR(0x8009CF44u, int)
#define D_8009CF48 PE_DECOMP_SCALAR(0x8009CF48u, int)

/* ── verbatim matching leaf (src/func_8005051C.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: D_8009CF44 */
/* shimmed by pe_guest_decomp.h: D_8009CF48 */

/* shimmed by pe_guest_decomp.h: func_80042170 */

void func_8005051C(void) {
    func_80042170(D_8009CF44, D_8009CF48);
}

