/*
 * decomp-source: func_800CCEE8
 * matched VMA 0x800CCEE8  file 0xBD6E8  span 0x28 bytes / 10 words
 * evidence: docs/evidence/func_800CCEE8/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800CCEE8.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_800E0E60 PE_DECOMP_ARRAY(0x800E0E60u, unsigned char)

/* ── verbatim matching leaf (src/func_800CCEE8.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: func_800C2414 */

/* shimmed by pe_guest_decomp.h: D_800E0E60 */

int func_800CCEE8(int arg0) {
    func_800C2414(arg0, (pe_addr_t)0x800E0E60u);
    return 0;
}

