/*
 * decomp-source: func_800C2B40
 * matched VMA 0x800C2B40  file 0xB3340  span 0x10 bytes / 4 words
 * evidence: docs/evidence/func_800C2B40/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800C2B40.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_800E2248 PE_DECOMP_PTRGLOBAL(0x800E2248u, unsigned char)

/* ── verbatim matching leaf (src/func_800C2B40.c) ───────────────────────── */

/* Phase 5G: first tail-region matching C leaf.
 * VRAM 0x800C2B40 / file 0xB3340 / size 0x10.
 * Original: lui/lw D_800E2248; jr; sw $a0, 0x70($v0)
 * Temporary types only — no semantic names for the table/field yet.
 * Same GCC flags as Phase 4J/5B–5F.
 */
/* shimmed by pe_guest_decomp.h: D_800E2248 */

void func_800C2B40(unsigned int arg0) {
    *(unsigned int *)(D_800E2248 + 0x70) = arg0;
}

