/*
 * decomp-source: func_80075C94
 * matched VMA 0x80075C94  file 0x66494  span 0x54 bytes / 21 words
 * evidence: docs/evidence/func_80075C94/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80075C94.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
/* verbatim callee declarations */
extern int func_80076150(int a0, int a1, int a2);
extern int func_800762BC(int a0);

void func_80075C94(pe_addr_t pe_a0, int a1, int a2, int a3, int a4)
{
    unsigned char *host_a0 = (unsigned char *)PE_Translate(pe_a0, 1);
    /* verbatim body (src/func_80075C94.c) */

    host_a0[3] = 2;
    *(int *)(host_a0 + 4) = func_80076150(a1, a2, a3 & 0xFFFF);
    *(int *)(host_a0 + 8) = func_800762BC(a4);

}
