/*
 * decomp-source: func_800864CC
 * matched VMA 0x800864CC  file 0x76CCC  span 0x2C bytes / 11 words
 * evidence: docs/evidence/func_800864CC/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800864CC.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_800BCD80 PE_DECOMP_SCALAR(0x800BCD80u, int)

/* ── verbatim matching leaf (src/func_800864CC.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: D_800BCD80 */
/* shimmed by pe_guest_decomp.h: func_8008CBA8 */
void func_800864CC(void) {
    D_800BCD80 = 0x40;
    func_8008CBA8();
}

