/*
 * decomp-source: func_80085DC4
 * matched VMA 0x80085DC4  file 0x765C4  span 0x24 bytes / 9 words
 * evidence: docs/evidence/func_80085DC4/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80085DC4.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* ── verbatim matching leaf (src/func_80085DC4.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: func_80073CC4 */

void func_80085DC4(int value) {
    func_80073CC4(9, value);
}

