/*
 * decomp-source: func_8008A02C
 * matched VMA 0x8008A02C  file 0x7A82C  span 0x3C bytes / 15 words
 * evidence: docs/evidence/func_8008A02C/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8008A02C.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
void func_8008A02C(pe_addr_t pe_a0, unsigned int a1, int a2)
{
    unsigned int *host_a0 = (unsigned int *)PE_Translate(pe_a0, 1);
    /* verbatim body (src/func_8008A02C.c) */

    unsigned int *p = host_a0 + 1;
    unsigned int d = a1 - *host_a0;
    do {
        *host_a0 += d;
        *p += d;
        host_a0 += 0x10;
        p += 0x10;
        a2--;
    } while (a2);

}
