/*
 * decomp-source: func_80017A24
 * matched VMA 0x80017A24  file 0x8224  span 0x2C bytes / 11 words
 * evidence: docs/evidence/func_80017A24/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80017A24.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
/* verbatim leaf types */
typedef struct {
    unsigned int *source;
    unsigned int *bit;
    unsigned int *destination;
} Arguments;

int func_80017A24(pe_addr_t pe_arg0)
{
    Arguments *host_arg0 = (Arguments *)PE_Translate(pe_arg0, 1);
    /* verbatim body (src/func_80017A24.c) */

    *host_arg0->destination = *host_arg0->source & (1U << *host_arg0->bit);
    return 1;

}
