/*
 * decomp-source: func_8008C70C
 * matched VMA 0x8008C70C  file 0x7CF0C  span 0x14 bytes / 5 words
 * evidence: docs/evidence/func_8008C70C/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8008C70C.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
/* verbatim leaf types */
typedef struct {
    char pad[0x56];
    short value;
} State;

void func_8008C70C(pe_addr_t pe_arg0)
{
    State *host_D_8009D2C8 = PE_DECOMP_PTRGLOBAL(0x8009D2C8u, State);
    int *host_arg0 = (int *)PE_Translate(pe_arg0, 1);
    /* verbatim body (src/func_8008C70C.c) */

    host_D_8009D2C8->value = host_arg0[1];

}
