/*
 * decomp-source: func_80076B20
 * matched VMA 0x80076B20  file 0x67320  span 0x24 bytes / 9 words
 * evidence: docs/evidence/func_80076B20/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80076B20.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_80095854 PE_DECOMP_PTRGLOBAL(0x80095854u, unsigned int)
#define D_800A3348 PE_DECOMP_ARRAY(0x800A3348u, unsigned char)

/* ── verbatim matching leaf (src/func_80076B20.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: D_80095854 */
/* shimmed by pe_guest_decomp.h: D_800A3348 */
void func_80076B20(unsigned int a0) {
    *D_80095854 = a0;
    D_800A3348[a0 >> 24] = a0;
}

