/*
 * decomp-source: func_8007633C
 * matched VMA 0x8007633C  file 0x66B3C  span 0x18 bytes / 6 words
 * evidence: docs/evidence/func_8007633C/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8007633C.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_80095854 PE_DECOMP_PTRGLOBAL(0x80095854u, int)

/* ── verbatim matching leaf (src/func_8007633C.c) ───────────────────────── */

/* Phase 5BU: seventieth matching C leaf (mid-654C8 carve).
 * VRAM 0x8007633C / file 0x66B3C / size 0x18.
 * Original: lui/lw/nop/lw 0/jr/nop on D_80095854.
 * Pointer double-deref getter; plain -O1 matches.
 */
/* shimmed by pe_guest_decomp.h: D_80095854 */

int func_8007633C(void) {
    return *D_80095854;
}

