/*
 * decomp-source: func_80051834
 * matched VMA 0x80051834  file 0x42034  span 0x18 bytes / 6 words
 * evidence: docs/evidence/func_80051834/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80051834.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_800C0E24 PE_DECOMP_SCALAR(0x800C0E24u, unsigned int)

/* ── verbatim matching leaf (src/func_80051834.c) ───────────────────────── */

/* Phase 5AV: forty-fifth matching C leaf (mid-41520 carve).
 * VRAM 0x80051834 / file 0x42034 / size 0x18.
 * Original: lui/lw/nop/srlv/jr/andi 1 on D_800C0E24.
 * Unsigned global bit test; plain Phase 4J -O1 emits the exact six words.
 */
/* shimmed by pe_guest_decomp.h: D_800C0E24 */

int func_80051834(int a0) {
    return (D_800C0E24 >> a0) & 1;
}

