/*
 * decomp-source: func_80091080
 * matched VMA 0x80091080  file 0x81880  span 0x20 bytes / 8 words
 * evidence: docs/evidence/func_80091080/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80091080.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* boundary: func_80090F68 has no pc_port implementation yet */
#define func_80090F68(...) PE_D_COMP_BOUNDARY0("func_80090F68", 0x80090F68u)


/* ── verbatim matching leaf (src/func_80091080.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: func_80090F68 */

void func_80091080(void) {
    func_80090F68();
}

