/*
 * decomp-source: func_80085134
 * matched VMA 0x80085134  file 0x75934  span 0x40 bytes / 16 words
 * evidence: docs/evidence/func_80085134/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80085134.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* boundary: func_800850C0 has no pc_port implementation yet */
#define func_800850C0(...) PE_D_COMP_BOUNDARY0("func_800850C0", 0x800850C0u)

/* boundary: func_80085DF4 has no pc_port implementation yet */
#define func_80085DF4(...) PE_D_COMP_BOUNDARY2("func_80085DF4", 0x80085DF4u, __VA_ARGS__)


/* ── verbatim matching leaf (src/func_80085134.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: func_800850C0 */
/* shimmed by pe_guest_decomp.h: func_80085DF4 */

void func_80085134(int arg0, int arg1) {
    func_800850C0();
    func_80085DF4(arg0, arg1);
}

