/*
 * decomp-source: func_800C9A34
 * matched VMA 0x800C9A34  file 0xBA234  span 0x3C bytes / 15 words
 * evidence: docs/evidence/func_800C9A34/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800C9A34.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
void func_800C9A34(pe_addr_t pe_unused, pe_addr_t pe_state, pe_addr_t pe_values)
{
    signed char *host_state = (signed char *)PE_Translate(pe_state, 1);
    unsigned short *host_values = (unsigned short *)PE_Translate(pe_values, 1);
    /* verbatim body (src/func_800C9A34.c) */

    host_values[2] -= 8;
    host_values[3] += 0x28;
    if ((short)host_values[2] < 20) {
        host_values[2] = 0;
        host_state[1] = 2;
    }

}
