/*
 * decomp-source: func_8007A324
 * matched VMA 0x8007A324  file 0x6AB24  span 0x10 bytes / 4 words
 * evidence: docs/evidence/func_8007A324/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8007A324.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009AFC4 PE_DECOMP_SCALAR(0x8009AFC4u, unsigned char)

/* ── verbatim matching leaf (src/func_8007A324.c) ───────────────────────── */

/* Phase 5BK: sixtieth matching C leaf (mid-65238 carve).
 * VRAM 0x8007A324 / file 0x6AB24 / size 0x10.
 * Original: lui $v0,%hi((pe_addr_t)0x8009AFC4u); lbu $v0,%lo((pe_addr_t)0x8009AFC4u)($v0);
 *           jr $ra; nop
 */
/* shimmed by pe_guest_decomp.h: D_8009AFC4 */

unsigned char func_8007A324(void) {
    return D_8009AFC4;
}

