/*
 * decomp-source: func_800813E8
 * matched VMA 0x800813E8  file 0x71BE8  span 0x20 bytes / 8 words
 * evidence: docs/evidence/func_800813E8/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800813E8.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* ── verbatim matching leaf (src/func_800813E8.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: func_8007C564 */

void func_800813E8(void) {
    func_8007C564();
}

