/*
 * decomp-source: func_80082554
 * matched VMA 0x80082554  file 0x72D54  span 0x20 bytes / 8 words
 * evidence: docs/evidence/func_80082554/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80082554.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* boundary: func_80082DBC has no pc_port implementation yet */
#define func_80082DBC(...) PE_D_COMP_BOUNDARY0("func_80082DBC", 0x80082DBCu)


/* ── verbatim matching leaf (src/func_80082554.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: func_80082DBC */

void func_80082554(void) {
    func_80082DBC();
}

