/*
 * decomp-source: func_80019050
 * matched VMA 0x80019050  file 0x9850  span 0x8 bytes / 2 words
 * evidence: docs/evidence/func_80019050/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80019050.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* ── verbatim matching leaf (src/func_80019050.c) ───────────────────────── */

/* Phase 5AL: thirty-fourth matching C leaf (mid-86A4 carve).
 * VRAM 0x80019050 / file 0x9850 / size 0x8.
 * Original: jr $ra; addiu $v0,$zero,1 — return-1 stub (li in delay slot).
 * Third of the seven byte-identical return-1 twins (2026-07-09 triage);
 * back-to-back with func_80019058 (next twin, file 0x9858).
 * Scratch probe (Phase 5AJ, same bytes): GCC 14.2 Phase 4J flags exact
 * 0x8-byte match (0800E003 01000224).
 */
int func_80019050(void) {
    return 1;
}

