/*
 * decomp-source: func_80016DF8
 * matched VMA 0x80016DF8  file 0x75F8  span 0x24 bytes / 9 words
 * evidence: docs/evidence/func_80016DF8/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80016DF8.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009D2F0 PE_DECOMP_PTRGLOBAL(0x8009D2F0u, State)

/* ── verbatim matching leaf (src/func_80016DF8.c) ───────────────────────── */

typedef struct {
    char pad[0x98];
    unsigned int flags;
} State;

/* shimmed by pe_guest_decomp.h: D_8009D2F0 */

int func_80016DF8(void) {
    D_8009D2F0->flags |= 0x20000000u;
    return 1;
}

