/*
 * decomp-source: func_8007DD14
 * matched VMA 0x8007DD14  file 0x6E514  span 0x24 bytes / 9 words
 * evidence: docs/evidence/func_8007DD14/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8007DD14.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* ── verbatim matching leaf (src/func_8007DD14.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: func_80073CF4 */

void func_8007DD14(unsigned int value) {
    func_80073CF4(4, value);
}

