/*
 * decomp-source: func_800C9260
 * matched VMA 0x800C9260  file 0xB9A60  span 0x8 bytes / 2 words
 * evidence: docs/evidence/func_800C9260/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800C9260.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* ── verbatim matching leaf (src/func_800C9260.c) ───────────────────────── */

/* Phase 5U: eighteenth matching C leaf (second mid-tail carve, from B8A70.s).
 * VRAM 0x800C9260 / file 0xB9A60 / size 0x8.
 * Original: jr $ra; nop — empty return stub.
 * Scratch probe: GCC 14.2 Phase 4J flags exact 0x8-byte match.
 */
void func_800C9260(void) {
}

