/*
 * decomp-source: func_8008FED8
 * matched VMA 0x8008FED8  file 0x806D8  span 0x24 bytes / 9 words
 * evidence: docs/evidence/func_8008FED8/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8008FED8.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
void func_8008FED8(pe_addr_t pe_a0)
{
    unsigned char *host_a0 = (unsigned char *)PE_Translate(pe_a0, 1);
    /* verbatim body (src/func_8008FED8.c) */

    *(unsigned int *)(host_a0 + 0x38) &= ~1u;
    *(unsigned short *)(host_a0 + 0xE8) = 0;
    *(unsigned int *)(host_a0 + 0xF4) |= 0x10u;

}
