/*
 * decomp-source: func_8005288C
 * matched VMA 0x8005288C  file 0x4308C  span 0x8 bytes / 2 words
 * evidence: docs/evidence/func_8005288C/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8005288C.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* ── verbatim matching leaf (src/func_8005288C.c) ───────────────────────── */

int func_8005288C(void) {
    return 0;
}

