/*
 * decomp-source: func_8007FC18
 * matched VMA 0x8007FC18  file 0x70418  span 0x10 bytes / 4 words
 * evidence: docs/evidence/func_8007FC18/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8007FC18.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009B581 PE_DECOMP_SCALAR(0x8009B581u, unsigned char)

/* ── verbatim matching leaf (src/func_8007FC18.c) ───────────────────────── */

/* Phase 5BF: fifty-fifth matching C leaf (mid-70418 carve).
 * VRAM 0x8007FC18 / file 0x70418 / size 0x10.
 * Original: lui $v0,%hi(D_8009B581); lbu $v0,%lo(D_8009B581)($v0);
 *           jr $ra; nop
 * Unsigned-byte global getter; plain Phase 4J -O1 emits the exact four words.
 */
/* shimmed by pe_guest_decomp.h: D_8009B581 */

unsigned char func_8007FC18(void) {
    return D_8009B581;
}

