/*
 * decomp-source: func_800614A0
 * matched VMA 0x800614A0  file 0x51CA0  span 0xC bytes / 3 words
 * evidence: docs/evidence/func_800614A0/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800614A0.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009D14C PE_DECOMP_SCALAR(0x8009D14Cu, int)

/* ── verbatim matching leaf (src/func_800614A0.c) ───────────────────────── */

/* Phase 5DC: gp-relative leaf func_800614A0.
 * VRAM 0x800614A0 / gp+0x3DC -> D_8009D14C. gp base 0x8009CD70.
 * -G 8 emits R_MIPS_GPREL16; _gp+abs sym resolve to retail offset. */
/* shimmed by pe_guest_decomp.h: D_8009D14C */
int func_800614A0(void){ return D_8009D14C; }

