/*
 * decomp-source: func_80074A14
 * matched VMA 0x80074A14  file 0x65214  span 0x14 bytes / 5 words
 * evidence: docs/evidence/func_80074A14/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80074A14.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_800956EC PE_DECOMP_SCALAR(0x800956ECu, unsigned int)

/* ── verbatim matching leaf (src/func_80074A14.c) ───────────────────────── */

/* Phase 5EF: exchange D_800956EC and return the prior value.
 * Reader provenance: low byte is stored, masked with 0xFF, and state-tested. */
/* shimmed by pe_guest_decomp.h: D_800956EC */

unsigned int func_80074A14(unsigned int value) {
    unsigned int old = D_800956EC;
    D_800956EC = value;
    return old;
}

