/*
 * decomp-source: func_8007A8AC
 * matched VMA 0x8007A8AC  file 0x6B0AC  span 0x20 bytes / 8 words
 * evidence: docs/evidence/func_8007A8AC/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8007A8AC.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* boundary: func_8007BF44 has no pc_port implementation yet */
#define func_8007BF44(...) PE_D_COMP_BOUNDARY0("func_8007BF44", 0x8007BF44u)


/* ── verbatim matching leaf (src/func_8007A8AC.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: func_8007BF44 */

int func_8007A8AC(void) {
    return !func_8007BF44();
}

