/*
 * decomp-source: func_80017C8C
 * matched VMA 0x80017C8C  file 0x848C  span 0x38 bytes / 14 words
 * evidence: docs/evidence/func_80017C8C/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80017C8C.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
/* verbatim leaf types */
typedef struct {
    short *first;
    short *second;
    unsigned short *third;
} Arguments;

int func_80017C8C(pe_addr_t pe_arg0)
{
    Arguments *host_arg0 = (Arguments *)PE_Translate(pe_arg0, 1);
    /* verbatim body (src/func_80017C8C.c) */

    func_800661EC(*host_arg0->first, *host_arg0->second, *host_arg0->third, 8);
    return 1;

}
