/*
 * decomp-source: func_80083E70
 * matched VMA 0x80083E70  file 0x74670  span 0x14 bytes / 5 words
 * evidence: docs/evidence/func_80083E70/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80083E70.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
void func_80083E70(pe_addr_t pe_arg0)
{
    unsigned char *host_arg0 = (unsigned char *)PE_Translate(pe_arg0, 1);
    /* verbatim body (src/func_80083E70.c) */

    host_arg0[0x36] = 0x45;
    *(unsigned int *)(host_arg0 + 0x2C) = 0;
    host_arg0[0x35] = 0;

}
