/*
 * decomp-source: func_80085F44
 * matched VMA 0x80085F44  file 0x76744  span 0x24 bytes / 9 words
 * evidence: docs/evidence/func_80085F44/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80085F44.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009B434 PE_DECOMP_SCALAR(0x8009B434u, int)

/* ── verbatim matching leaf (src/func_80085F44.c) ───────────────────────── */

/* Change-guarded setter: read the current value, overwrite only on a change,
 * and return the previous value. VRAM 0x80085F44 / file 0x76744 / size 0x24. */
/* shimmed by pe_guest_decomp.h: D_8009B434 */

int func_80085F44(int a0) {
    int v0 = D_8009B434;
    if (a0 != v0)
        D_8009B434 = a0;
    return v0;
}

