/*
 * decomp-source: func_8007DFE0
 * matched VMA 0x8007DFE0  file 0x6E7E0  span 0x30 bytes / 12 words
 * evidence: docs/evidence/func_8007DFE0/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8007DFE0.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* boundary: func_8007E1B4 has no pc_port implementation yet */
#define func_8007E1B4(...) PE_D_COMP_BOUNDARY0("func_8007E1B4", 0x8007E1B4u)

/* boundary: func_8007E204 has no pc_port implementation yet */
#define func_8007E204(...) PE_D_COMP_BOUNDARY0("func_8007E204", 0x8007E204u)


/* ── verbatim matching leaf (src/func_8007DFE0.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: func_8007E1B4 */
/* shimmed by pe_guest_decomp.h: func_80073C74 */
/* shimmed by pe_guest_decomp.h: func_8007E204 */
int func_8007DFE0(void) {
    func_8007E1B4();
    func_80073C74(0);
    func_8007E204();
    return 1;
}

