/*
 * decomp-source: func_8005E4E4
 * matched VMA 0x8005E4E4  file 0x4ECE4  span 0x34 bytes / 13 words
 * evidence: docs/evidence/func_8005E4E4/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8005E4E4.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009D0E8 PE_DECOMP_SCALAR(0x8009D0E8u, int)

/* ── verbatim matching leaf (src/func_8005E4E4.c) ───────────────────────── */

/*
 * func_8005E4E4 — gp-guarded call result, bit 0x20 normalised to 0/1.
 * VRAM 0x8005E4E4 / file 0x4ECE4 / size 0x34. era -O2 -G8.
 */
/* shimmed by pe_guest_decomp.h: D_8009D0E8 */

int func_8005E4E4(void) {
    int r = 0;
    if (D_8009D0E8) {
        unsigned int v = func_8005E038() & 0x20;
        r = (v > 0);
    }
    return r;
}

