/*
 * decomp-source: func_800375D0
 * matched VMA 0x800375D0  file 0x27DD0  span 0x10 bytes / 4 words
 * evidence: docs/evidence/func_800375D0/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800375D0.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009CED4 PE_DECOMP_SCALAR(0x8009CED4u, int)

/* ── verbatim matching leaf (src/func_800375D0.c) ───────────────────────── */

/* Phase 5DE: gp-relative setter func_800375D0 (-G 8 -fno-delayed-branch). */
/* shimmed by pe_guest_decomp.h: D_8009CED4 */
void func_800375D0(int a0){ D_8009CED4 = (a0 != 0); }

