/*
 * decomp-source: func_800193B8
 * matched VMA 0x800193B8  file 0x9BB8  span 0x20 bytes / 8 words
 * evidence: docs/evidence/func_800193B8/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800193B8.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* ── verbatim matching leaf (src/func_800193B8.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: func_800703F4 */

int func_800193B8(void) {
    func_800703F4();
    return 1;
}

