/*
 * decomp-source: func_80052524
 * matched VMA 0x80052524  file 0x42D24  span 0x10 bytes / 4 words
 * evidence: docs/evidence/func_80052524/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80052524.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_800C0E32 PE_DECOMP_SCALAR(0x800C0E32u, unsigned short)

/* ── verbatim matching leaf (src/func_80052524.c) ───────────────────────── */

/* Phase 5AS: forty-second matching C leaf (zero-prefix carve of 42D24.s).
 * VRAM 0x80052524 / file 0x42D24 / size 0x10.
 * Original: lui $v0,%hi(D_800C0E32); lhu $v0,%lo(D_800C0E32)($v0); jr $ra; nop
 * 16-bit unsigned global getter (returns D_800C0E32).
 * Twin of func_80052514 (D_800C0E28) — identical shape; plain Phase 4J -O1
 * matches (MIPS-I load-delay keeps lhu out of the jr delay slot).
 */
/* shimmed by pe_guest_decomp.h: D_800C0E32 */

unsigned short func_80052524(void) {
    return D_800C0E32;
}

