/*
 * decomp-source: func_8008FED8
 * matched VMA 0x8008FED8  file 0x806D8  span 0x24 bytes / 9 words
 * evidence: docs/evidence/func_8008FED8/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8008FED8.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* ── verbatim matching leaf (src/func_8008FED8.c) ───────────────────────── */

/* Clear one flag bit, set another status bit, and zero a halfword.
 * VRAM 0x8008FED8 / file 0x806D8 / size 0x24. */
void func_8008FED8(int a0) {
    int v0 /* host: MIPS register binding dropped */;
    int v1 /* host: MIPS register binding dropped */;

    v0 = *(int *)(a0 + 0x38);
    v1 = *(int *)(a0 + 0xF4);
    *(short *)(a0 + 0xE8) = 0;
    v0 &= -2;
    v1 |= 0x10;
    *(int *)(a0 + 0x38) = v0;
    *(int *)(a0 + 0xF4) = v1;
}

