/*
 * decomp-source: func_80042CB8
 * matched VMA 0x80042CB8  file 0x334B8  span 0xC bytes / 3 words
 * evidence: docs/evidence/func_80042CB8/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80042CB8.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009CEEC PE_DECOMP_SCALAR(0x8009CEECu, int)

/* ── verbatim matching leaf (src/func_80042CB8.c) ───────────────────────── */

/* Phase 5DC: gp-relative leaf func_80042CB8.
 * VRAM 0x80042CB8 / gp+0x17C -> D_8009CEEC. gp base 0x8009CD70.
 * -G 8 emits R_MIPS_GPREL16; _gp+abs sym resolve to retail offset. */
/* shimmed by pe_guest_decomp.h: D_8009CEEC */
void func_80042CB8(int a0){ D_8009CEEC = a0; }

