/*
 * decomp-source: func_80080B04
 * matched VMA 0x80080B04  file 0x71304  span 0x20 bytes / 8 words
 * evidence: docs/evidence/func_80080B04/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80080B04.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
/* boundary: func_8007C044 has no pc_port implementation yet */
#define func_8007C044(...) PE_D_COMP_BOUNDARY2("func_8007C044", 0x8007C044u, __VA_ARGS__)

int func_80080B04(pe_addr_t pe_buffer, int value)
{
    /* verbatim body (src/func_80080B04.c) */

    return func_8007C044( pe_buffer, value) == 0;

}
