/*
 * decomp-source: func_800C7DDC
 * matched VMA 0x800C7DDC  file 0xB85DC  span 0x8 bytes / 2 words
 * evidence: docs/evidence/func_800C7DDC/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800C7DDC.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* ── verbatim matching leaf (src/func_800C7DDC.c) ───────────────────────── */

/* Phase 5EB: era return-0 twin. Same shape as func_8003DFD0.
 * jr $ra; addu $v0,$zero,$zero — compiled via era_compile -O2 -G0. */
int func_800C7DDC(void){ return 0; }

