/*
 * decomp-source: func_80086568
 * matched VMA 0x80086568  file 0x76D68  span 0x3C bytes / 15 words
 * evidence: docs/evidence/func_80086568/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80086568.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_800BCD80 PE_DECOMP_SCALAR(0x800BCD80u, int)
#define D_800BCD84 PE_DECOMP_SCALAR(0x800BCD84u, int)
#define D_800BCD88 PE_DECOMP_SCALAR(0x800BCD88u, int)

/* ── verbatim matching leaf (src/func_80086568.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: D_800BCD80, (pe_addr_t)0x800BCD84u, D_800BCD88 */
/* shimmed by pe_guest_decomp.h: func_8008CBA8 */
void func_80086568(int a0, int a1) { D_800BCD80 = 0x12; D_800BCD84 = a0; D_800BCD88 = a1; func_8008CBA8(); }

