/*
 * decomp-source: func_8007A400
 * matched VMA 0x8007A400  file 0x6AC00  span 0x34 bytes / 13 words
 * evidence: docs/evidence/func_8007A400/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8007A400.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009AFDC PE_DECOMP_ARRAY(0x8009AFDCu, unsigned int)
#define D_800119CC PE_DECOMP_ARRAY(0x800119CCu, unsigned char)

/* ── verbatim matching leaf (src/func_8007A400.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: D_8009AFDC */
/* shimmed by pe_guest_decomp.h: D_800119CC */
unsigned int func_8007A400(unsigned int a0) {
    unsigned int i = a0 & 0xFF;
    if (i >= 0x1C) return (unsigned int)D_800119CC;
    return D_8009AFDC[i];
}

