/*
 * decomp-source: func_8007DC5C
 * matched VMA 0x8007DC5C  file 0x6E45C  span 0x28 bytes / 10 words
 * evidence: docs/evidence/func_8007DC5C/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8007DC5C.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009B410 PE_DECOMP_PTRGLOBAL(0x8009B410u, unsigned int)

/* ── verbatim matching leaf (src/func_8007DC5C.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: D_8009B410 */

void func_8007DC5C(void) {
    *D_8009B410 = (*D_8009B410 & 0xF0FFFFFF) | 0x20000000;
}

