/*
 * decomp-source: func_8007DEA4
 * matched VMA 0x8007DEA4  file 0x6E6A4  span 0xC bytes / 3 words
 * evidence: docs/evidence/func_8007DEA4/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8007DEA4.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009B4AC PE_DECOMP_SCALAR(0x8009B4ACu, unsigned int)

/* ── verbatim matching leaf (src/func_8007DEA4.c) ───────────────────────── */

/* Phase 5EF: opaque 32-bit setter.
 * Readers are branch-only; refine if a narrowing reader is found. */
/* shimmed by pe_guest_decomp.h: D_8009B4AC */

void func_8007DEA4(unsigned int value) {
    D_8009B4AC = value;
}

