/*
 * decomp-source: func_8007FC44
 * matched VMA 0x8007FC44  file 0x70444  span 0x10 bytes / 4 words
 * evidence: docs/evidence/func_8007FC44/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8007FC44.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009B587 PE_DECOMP_SCALAR(0x8009B587u, unsigned char)

/* ── verbatim matching leaf (src/func_8007FC44.c) ───────────────────────── */

/* Phase 5BH: fifty-seventh matching C leaf (mid-70428 carve).
 * VRAM 0x8007FC44 / file 0x70444 / size 0x10.
 * Original: lui $v0,%hi((pe_addr_t)0x8009B587u); lbu $v0,%lo((pe_addr_t)0x8009B587u)($v0);
 *           jr $ra; nop
 */
/* shimmed by pe_guest_decomp.h: D_8009B587 */

unsigned char func_8007FC44(void) {
    return D_8009B587;
}

