/*
 * decomp-source: func_80038910
 * matched VMA 0x80038910  file 0x29110  span 0x30 bytes / 12 words
 * evidence: docs/evidence/func_80038910/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80038910.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009CEB8 PE_DECOMP_SCALAR(0x8009CEB8u, unsigned short)
#define D_8009CEBC PE_DECOMP_SCALAR(0x8009CEBCu, unsigned short)
#define D_8009CEC0 PE_DECOMP_SCALAR(0x8009CEC0u, unsigned short)
#define D_8009CEB4 PE_DECOMP_SCALAR(0x8009CEB4u, unsigned char)
#define D_8009CEC4 PE_DECOMP_SCALAR(0x8009CEC4u, unsigned char)
#define D_8009CEC8 PE_DECOMP_SCALAR(0x8009CEC8u, unsigned char)
#define D_8009CECC PE_DECOMP_SCALAR(0x8009CECCu, unsigned char)

/* ── verbatim matching leaf (src/func_80038910.c) ───────────────────────── */

/*
 * func_80038910 — seed a fixed gp-relative record from six arguments.
 * VRAM 0x80038910 / file 0x29110 / size 0x30 (12 words).
 *
 * Args 5 and 6 arrive on the stack (0x10/0x14($sp)); the first four are in
 * $a0..$a3. Destinations are gp-relative: halfwords at 0x148/0x14C/0x150 and
 * bytes at 0x144/0x154/0x158/0x15C. era -O2 -G8.
 */
/* shimmed by pe_guest_decomp.h: D_8009CEB8 */
/* shimmed by pe_guest_decomp.h: D_8009CEBC */
/* shimmed by pe_guest_decomp.h: D_8009CEC0 */
/* shimmed by pe_guest_decomp.h: D_8009CEB4 */
/* shimmed by pe_guest_decomp.h: D_8009CEC4 */
/* shimmed by pe_guest_decomp.h: D_8009CEC8 */
/* shimmed by pe_guest_decomp.h: D_8009CECC */

void func_80038910(unsigned int a0, unsigned int a1, unsigned int a2,
                   unsigned int a3, unsigned char a4, unsigned char a5) {
    D_8009CEB8 = a0;
    D_8009CEB4 = 1;
    D_8009CEBC = a1;
    D_8009CEC0 = a2;
    D_8009CEC4 = a3;
    D_8009CEC8 = a4;
    D_8009CECC = a5;
}

