/*
 * decomp-source: func_80018BC8
 * matched VMA 0x80018BC8  file 0x93C8  span 0x24 bytes / 9 words
 * evidence: docs/evidence/func_80018BC8/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80018BC8.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009D2F0 PE_DECOMP_PTRGLOBAL(0x8009D2F0u, char)

/* ── verbatim matching leaf (src/func_80018BC8.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: D_8009D2F0 */

int func_80018BC8(void) {
    *(unsigned int *)(D_8009D2F0 + 0x98) &= ~0x20;
    return 1;
}

