/*
 * decomp-source: func_80075C04
 * matched VMA 0x80075C04  file 0x66404  span 0x40 bytes / 16 words
 * evidence: docs/evidence/func_80075C04/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80075C04.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
/* verbatim callee declarations */
extern int func_800762A0(int a0, int a1);

void func_80075C04(pe_addr_t pe_a0, pe_addr_t pe_a1)
{
    unsigned char *host_a0 = (unsigned char *)PE_Translate(pe_a0, 1);
    short *host_a1 = (short *)PE_Translate(pe_a1, 1);
    /* verbatim body (src/func_80075C04.c) */

    host_a0[3] = 2;
    *(int *)(host_a0 + 4) = func_800762A0(host_a1[0], host_a1[1]);
    *(int *)(host_a0 + 8) = 0;

}
