/*
 * decomp-source: func_800504F4
 * matched VMA 0x800504F4  file 0x40CF4  span 0x28 bytes / 10 words
 * evidence: docs/evidence/func_800504F4/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800504F4.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009CF44 PE_DECOMP_SCALAR(0x8009CF44u, int)
#define D_8009CF48 PE_DECOMP_SCALAR(0x8009CF48u, int)

/* boundary: func_80042020 has no pc_port implementation yet */
#define func_80042020(...) PE_D_COMP_BOUNDARY2("func_80042020", 0x80042020u, __VA_ARGS__)


/* ── verbatim matching leaf (src/func_800504F4.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: D_8009CF44 */
/* shimmed by pe_guest_decomp.h: D_8009CF48 */

/* shimmed by pe_guest_decomp.h: func_80042020 */

void func_800504F4(void) {
    func_80042020((pe_addr_t)0x8009CF44u, D_8009CF48);
}

