/*
 * decomp-source: func_8004E94C
 * matched VMA 0x8004E94C  file 0x3F14C  span 0x24 bytes / 9 words
 * evidence: docs/evidence/func_8004E94C/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8004E94C.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009CF0C PE_DECOMP_SCALAR(0x8009CF0Cu, int)

/* boundary: func_8004E704 has no pc_port implementation yet */
#define func_8004E704(...) PE_D_COMP_BOUNDARY1("func_8004E704", 0x8004E704u, __VA_ARGS__)


/* ── verbatim matching leaf (src/func_8004E94C.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: D_8009CF0C */

/* shimmed by pe_guest_decomp.h: func_8004E704 */

void func_8004E94C(void) {
    func_8004E704(D_8009CF0C - 1);
}

