/*
 * decomp-source: func_80019CEC
 * matched VMA 0x80019CEC  file 0xA4EC  span 0x38 bytes / 14 words
 * evidence: docs/evidence/func_80019CEC/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80019CEC.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009D2F0 PE_DECOMP_PTRGLOBAL(0x8009D2F0u, int)

/* ── verbatim matching leaf (src/func_80019CEC.c) ───────────────────────── */

/* VRAM 0x80019CEC / file 0xA4EC / size 0x38. */
/* shimmed by pe_guest_decomp.h: D_8009D2F0 */

int func_80019CEC(void) {
    *(int *)((char *)D_8009D2F0 + 0x28) = *(short *)((char *)D_8009D2F0 + 0x21C) << 16;
    *(int *)((char *)D_8009D2F0 + 0x2C) = *(short *)((char *)D_8009D2F0 + 0x21E) << 16;
    *(int *)((char *)D_8009D2F0 + 0x30) = *(short *)((char *)D_8009D2F0 + 0x220) << 16;
    return 1;
}

