/*
 * decomp-source: func_80089CF0
 * matched VMA 0x80089CF0  file 0x7A4F0  span 0x20 bytes / 8 words
 * evidence: docs/evidence/func_80089CF0/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80089CF0.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009D2C4 PE_DECOMP_SCALAR(0x8009D2C4u, unsigned int)

/* ── verbatim matching leaf (src/func_80089CF0.c) ───────────────────────── */

/* Set the display-state enable bit.
 * VRAM 0x80089CF0 / file 0x7A4F0 / size 0x20.
 */
/* shimmed by pe_guest_decomp.h: D_8009D2C4 */

void func_80089CF0(void) {
    D_8009D2C4 |= 0x100;
}

