/*
 * decomp-source: func_8007C130
 * matched VMA 0x8007C130  file 0x6C930  span 0xC bytes / 3 words
 * evidence: docs/evidence/func_8007C130/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8007C130.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009B260 PE_DECOMP_SCALAR(0x8009B260u, unsigned int)

/* ── verbatim matching leaf (src/func_8007C130.c) ───────────────────────── */

/* Phase 5EF: write-only opaque 32-bit setter.
 * No YAML-live reader narrows signedness, pointer-ness, or semantics. */
/* shimmed by pe_guest_decomp.h: D_8009B260 */

void func_8007C130(unsigned int value) {
    D_8009B260 = value;
}

