/*
 * decomp-source: func_800CCA40
 * matched VMA 0x800CCA40  file 0xBD240  span 0x38 bytes / 14 words
 * evidence: docs/evidence/func_800CCA40/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800CCA40.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
void func_800CCA40(int a0, pe_addr_t pe_a1, pe_addr_t pe_a2)
{
    unsigned char *host_a1 = (unsigned char *)PE_Translate(pe_a1, 1);
    unsigned char *host_a2 = (unsigned char *)PE_Translate(pe_a2, 1);
    /* verbatim body (src/func_800CCA40.c) */

    *(unsigned char *)(host_a2 + 3) -= 2;
    *(unsigned short *)(host_a2 + 4) += 0x28;
    if (*(signed char *)(host_a2 + 3) < 0x1E)
        host_a1[1] = 2;

}
