/*
 * decomp-source: func_800C2B68
 * matched VMA 0x800C2B68  file 0xB3368  span 0x28 bytes / 10 words
 * evidence: docs/evidence/func_800C2B68/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800C2B68.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_800E2248 PE_DECOMP_PTRGLOBAL(0x800E2248u, State)

/* ── verbatim matching leaf (src/func_800C2B68.c) ───────────────────────── */

typedef struct {
    char pad[4];
    unsigned int value;
} State;

/* shimmed by pe_guest_decomp.h: D_800E2248 */

int func_800C2B68(void) {
    return (D_800E2248->value & 0xFFFF0000U) == 0x01010000U;
}

