/*
 * decomp-source: func_8007DE78
 * matched VMA 0x8007DE78  file 0x6E678  span 0x28 bytes / 10 words
 * evidence: docs/evidence/func_8007DE78/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8007DE78.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* boundary: func_8007E334 has no pc_port implementation yet */
#define func_8007E334(...) PE_D_COMP_BOUNDARY0("func_8007E334", 0x8007E334u)

/* boundary: func_8007E514 has no pc_port implementation yet */
#define func_8007E514(...) PE_D_COMP_BOUNDARY0("func_8007E514", 0x8007E514u)


/* ── verbatim matching leaf (src/func_8007DE78.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: func_8007E334 */
/* shimmed by pe_guest_decomp.h: func_8007E514 */

void func_8007DE78(void) {
    func_8007E334();
    func_8007E514();
}

