/*
 * decomp-source: func_80073DF8
 * matched VMA 0x80073DF8  file 0x645F8  span 0x18 bytes / 6 words
 * evidence: docs/evidence/func_80073DF8/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80073DF8.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_80095674 PE_DECOMP_PTRGLOBAL(0x80095674u, unsigned short)

/* ── verbatim matching leaf (src/func_80073DF8.c) ───────────────────────── */

/* Phase 5BX: seventy-third matching C leaf (zero-prefix carve of 645F8.s).
 * VRAM 0x80073DF8 / file 0x645F8 / size 0x18.
 * Original: lui/lw/nop/lhu 0/jr/nop on D_80095674.
 * Halfword pointer deref; plain -O1 matches.
 */
/* shimmed by pe_guest_decomp.h: D_80095674 */

unsigned short func_80073DF8(void) {
    return *D_80095674;
}

