/*
 * decomp-source: func_800534CC
 * matched VMA 0x800534CC  file 0x43CCC  span 0x18 bytes / 6 words
 * evidence: docs/evidence/func_800534CC/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800534CC.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#undef D_8009D048
#define D_8009D048 PE_DECOMP_PTRGLOBAL(0x8009D048u, short)

/* ── verbatim matching leaf (src/func_800534CC.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: D_8009D048 */

short func_800534CC(int index) {
    return D_8009D048[index];
}

