/*
 * decomp-source: func_800867E4
 * matched VMA 0x800867E4  file 0x76FE4  span 0x48 bytes / 18 words
 * evidence: docs/evidence/func_800867E4/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800867E4.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_800BCD80 PE_DECOMP_SCALAR(0x800BCD80u, int)

/* ── verbatim matching leaf (src/func_800867E4.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: D_800BCD80 */
/* shimmed by pe_guest_decomp.h: func_8008CBA8 */
void func_800867E4(int a0) { int v; switch (a0) { case 1: v=0x9B; break; case 2: v=0x9D; break; default: v=0x99; break; } D_800BCD80=v; func_8008CBA8(); }

