/*
 * decomp-source: func_80074A28
 * matched VMA 0x80074A28  file 0x65228  span 0x10 bytes / 4 words
 * evidence: docs/evidence/func_80074A28/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80074A28.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_800956EC PE_DECOMP_SCALAR(0x800956ECu, int)

/* ── verbatim matching leaf (src/func_80074A28.c) ───────────────────────── */

/* Phase 5AX: forty-seventh matching C leaf (mid-645F8 carve).
 * VRAM 0x80074A28 / file 0x65228 / size 0x10.
 * Original: lui $v0,%hi(D_800956EC); lw $v0,%lo(D_800956EC)($v0);
 *           jr $ra; nop
 * 32-bit global getter; plain Phase 4J -O1 emits the exact four words.
 *
 * Clean re-derivation from 7902dd2 (5AW / 46 leaves) after a prior 5AX
 * attempt's safety claim (empty diff vs c3a8424) was found unverifiable.
 */
/* shimmed by pe_guest_decomp.h: D_800956EC */

int func_80074A28(void) {
    return D_800956EC;
}

