/*
 * decomp-source: func_800847A0
 * matched VMA 0x800847A0  file 0x74FA0  span 0x10 bytes / 4 words
 * evidence: docs/evidence/func_800847A0/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800847A0.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
void func_800847A0(pe_addr_t pe_arg0)
{
    unsigned char *host_arg0 = (unsigned char *)PE_Translate(pe_arg0, 1);
    /* verbatim body (src/func_800847A0.c) */

    unsigned char v0 = host_arg0[0x36];
    host_arg0[0x36] = 0;
    host_arg0[0x37] = v0;

}
