/*
 * decomp-source: func_8004F448
 * matched VMA 0x8004F448  file 0x3FC48  span 0x1C bytes / 7 words
 * evidence: docs/evidence/func_8004F448/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8004F448.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009CF98 PE_DECOMP_SCALAR(0x8009CF98u, int)
#define D_8009D008 PE_DECOMP_SCALAR(0x8009D008u, int)

/* ── verbatim matching leaf (src/func_8004F448.c) ───────────────────────── */

/* Phase 5EG: first branchy leaf func_8004F448 (-G 8, delay slots on). */
/* shimmed by pe_guest_decomp.h: D_8009CF98 */
/* shimmed by pe_guest_decomp.h: D_8009D008 */
void func_8004F448(void) { if (D_8009CF98 != 0) D_8009D008 = 1; }

