/*
 * decomp-source: func_80080AC4
 * matched VMA 0x80080AC4  file 0x712C4  span 0x20 bytes / 8 words
 * evidence: docs/evidence/func_80080AC4/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80080AC4.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
int func_80080AC4(pe_addr_t pe_buffer)
{
    /* verbatim body (src/func_80080AC4.c) */

    func_8007B964( pe_buffer);
    return 1;

}
