/*
 * decomp-source: func_80090178
 * matched VMA 0x80090178  file 0x80978  span 0x24 bytes / 9 words
 * evidence: docs/evidence/func_80090178/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80090178.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* ── verbatim matching leaf (src/func_80090178.c) ───────────────────────── */

/* Clear one flag bit, set another status bit, and zero a halfword.
 * VRAM 0x80090178 / file 0x80978 / size 0x24. */
void func_80090178(int a0) {
    int v0 /* host: MIPS register binding dropped */;
    int v1 /* host: MIPS register binding dropped */;

    v0 = *(int *)(a0 + 0x38);
    v1 = *(int *)(a0 + 0xF4);
    *(short *)(a0 + 0xEC) = 0;
    v0 &= -5;
    v1 |= 0x3;
    *(int *)(a0 + 0x38) = v0;
    *(int *)(a0 + 0xF4) = v1;
}

