/*
 * decomp-source: func_800C2B50
 * matched VMA 0x800C2B50  file 0xB3350  span 0x18 bytes / 6 words
 * evidence: docs/evidence/func_800C2B50/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800C2B50.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_800E2248 PE_DECOMP_PTRGLOBAL(0x800E2248u, int)

/* ── verbatim matching leaf (src/func_800C2B50.c) ───────────────────────── */

/* Phase 5BW: seventy-second matching C leaf (zero-prefix carve of B3350.s).
 * VRAM 0x800C2B50 / file 0xB3350 / size 0x18.
 * Original: lui/lw/nop/lw 0x70/jr/nop on D_800E2248.
 * Pointer field getter at +0x70; plain -O1 matches.
 */
/* shimmed by pe_guest_decomp.h: D_800E2248 */

int func_800C2B50(void) {
    return D_800E2248[0x1C];
}

