/*
 * decomp-source: func_800CBC2C
 * matched VMA 0x800CBC2C  file 0xBC42C  span 0x3C bytes / 15 words
 * evidence: docs/evidence/func_800CBC2C/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800CBC2C.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
void func_800CBC2C(int a0, pe_addr_t pe_a1, pe_addr_t pe_a2)
{
    unsigned char *host_a1 = (unsigned char *)PE_Translate(pe_a1, 1);
    unsigned char *host_a2 = (unsigned char *)PE_Translate(pe_a2, 1);
    /* verbatim body (src/func_800CBC2C.c) */

    *(unsigned short *)(host_a2 + 4) -= 8;
    *(unsigned short *)(host_a2 + 6) += 0x78;
    if (*(short *)(host_a2 + 4) < 0x14) {
        *(unsigned short *)(host_a2 + 4) = 0;
        host_a1[1] = 2;
    }

}
