/*
 * decomp-source: func_8003FFBC
 * matched VMA 0x8003FFBC  file 0x307BC  span 0x10 bytes / 4 words
 * evidence: docs/evidence/func_8003FFBC/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8003FFBC.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_800A1704 PE_DECOMP_SCALAR(0x800A1704u, int)

/* ── verbatim matching leaf (src/func_8003FFBC.c) ───────────────────────── */

/* Phase 5AT: forty-third matching C leaf (mid-2E7D0 carve).
 * VRAM 0x8003FFBC / file 0x307BC / size 0x10.
 * Original: lui $v0,%hi(D_800A1704); lw $v0,%lo(D_800A1704)($v0); jr $ra; nop
 * 32-bit global getter (returns D_800A1704).
 * Same load-return schedule as the 16-bit twins (5AR/5AS): plain Phase 4J
 * -O1 matches (MIPS-I load-delay keeps lw out of the jr delay slot).
 * Setter twin func_8003FFAC joined this getter in Phase 5EE via the era path.
 */
/* shimmed by pe_guest_decomp.h: D_800A1704 */

int func_8003FFBC(void) {
    return D_800A1704;
}

