/*
 * decomp-source: func_8008C6D0
 * matched VMA 0x8008C6D0  file 0x7CED0  span 0x3C bytes / 15 words
 * evidence: docs/evidence/func_8008C6D0/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8008C6D0.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
void func_8008C6D0(pe_addr_t pe_a0)
{
    unsigned char *host_D_800B8BB4 = PE_DECOMP_PTRGLOBAL(0x800B8BB4u, unsigned char);
    unsigned int *host_D_8009D2B8 = &PE_DECOMP_SCALAR(0x8009D2B8u, unsigned int);
    unsigned char *host_a0 = (unsigned char *)PE_Translate(pe_a0, 1);
    /* verbatim body (src/func_8008C6D0.c) */

    unsigned int i = 0;
    unsigned char *p = host_D_800B8BB4;
    (*host_D_8009D2B8) = *(unsigned int *)(host_a0 + 4);
    do {
        *(unsigned int *)p |= 3;
        i++;
        p += 0x11C;
    } while (i < 0x18);

}
