/*
 * decomp-source: func_8004D27C
 * matched VMA 0x8004D27C  file 0x3DA7C  span 0xC bytes / 3 words
 * evidence: docs/evidence/func_8004D27C/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8004D27C.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009CF50 PE_DECOMP_SCALAR(0x8009CF50u, int)

/* ── verbatim matching leaf (src/func_8004D27C.c) ───────────────────────── */

/* Phase 5DC: gp-relative leaf func_8004D27C.
 * VRAM 0x8004D27C / gp+0x1E0 -> D_8009CF50. gp base 0x8009CD70.
 * -G 8 emits R_MIPS_GPREL16; _gp+abs sym resolve to retail offset. */
/* shimmed by pe_guest_decomp.h: D_8009CF50 */
int func_8004D27C(void){ return D_8009CF50; }

