/*
 * decomp-source: func_8008A02C
 * matched VMA 0x8008A02C  file 0x7A82C  span 0x3C bytes / 15 words
 * evidence: docs/evidence/func_8008A02C/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8008A02C.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
void func_8008A02C(pe_addr_t pe_a0, int a1, int a2)
{
    unsigned char *host_a0 = (unsigned char *)PE_Translate(pe_a0, 1);
    /* verbatim body (src/func_8008A02C.c) */

    int delta = a1 - *(int *)host_a0;
    unsigned char *p = host_a0 + 4;
    do {
        *(int *)host_a0 += delta;
        host_a0 += 0x40;
        *(int *)p += delta;
        p += 0x40;
        a2--;
    } while (a2 != 0);

}
