/*
 * decomp-source: func_800CE470
 * matched VMA 0x800CE470  file 0xBEC70  span 0x2C bytes / 11 words
 * evidence: docs/evidence/func_800CE470/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800CE470.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
void func_800CE470(pe_addr_t pe_unused, pe_addr_t pe_state, pe_addr_t pe_counter)
{
    signed char *host_state = (signed char *)PE_Translate(pe_state, 1);
    signed char *host_counter = (signed char *)PE_Translate(pe_counter, 1);
    /* verbatim body (src/func_800CE470.c) */

    if (++host_counter[3] == 6) {
        host_state[1] = 2;
    }

}
