/*
 * decomp-source: func_8007A910
 * matched VMA 0x8007A910  file 0x6B110  span 0x20 bytes / 8 words
 * evidence: docs/evidence/func_8007A910/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8007A910.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* boundary: func_8007BDDC has no pc_port implementation yet */
#define func_8007BDDC(...) PE_D_COMP_BOUNDARY0("func_8007BDDC", 0x8007BDDCu)


/* ── verbatim matching leaf (src/func_8007A910.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: func_8007BDDC */

void func_8007A910(void) {
    func_8007BDDC();
}

