/*
 * decomp-source: func_80086B60
 * matched VMA 0x80086B60  file 0x77360  span 0x58 bytes / 22 words
 * evidence: docs/evidence/func_80086B60/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80086B60.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_800BCD80 PE_DECOMP_SCALAR(0x800BCD80u, int)
#define D_800BCD84 PE_DECOMP_SCALAR(0x800BCD84u, int)
#define D_800BCD88 PE_DECOMP_SCALAR(0x800BCD88u, int)
#define D_800BCD8C PE_DECOMP_SCALAR(0x800BCD8Cu, int)

/* ── verbatim matching leaf (src/func_80086B60.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: D_800BCD80, (pe_addr_t)0x800BCD84u, D_800BCD88, D_800BCD8C */
/* shimmed by pe_guest_decomp.h: func_8008CBA8 */
void func_80086B60(int a0, int a1, int a2) { D_800BCD80=0xA4; D_800BCD84=a0&0xFFFF; D_800BCD88=a1&0xFFFFFF; D_800BCD8C=a2&0xFF; func_8008CBA8(); }

