/*
 * decomp-source: func_8004BCB4
 * matched VMA 0x8004BCB4  file 0x3C4B4  span 0x34 bytes / 13 words
 * evidence: docs/evidence/func_8004BCB4/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8004BCB4.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* ── verbatim matching leaf (src/func_8004BCB4.c) ───────────────────────── */

/* VRAM 0x8004BCB4 / file 0x3C4B4 / size 0x34.
 * Set a message option then submit text id 0x19. */
/* shimmed by pe_guest_decomp.h: func_8005E8A4 */
/* shimmed by pe_guest_decomp.h: func_8005DC4C */
/* shimmed by pe_guest_decomp.h: func_8005F594 */
void func_8004BCB4(void) {
    func_8005E8A4(0, 4);
    func_8005F594(func_8005DC4C(0x19));
}

