/*
 * decomp-source: func_80074478
 * matched VMA 0x80074478  file 0x64C78  span 0x2C bytes / 11 words
 * evidence: docs/evidence/func_80074478/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80074478.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009568C PE_DECOMP_ARRAY(0x8009568Cu, int)

/* ── verbatim matching leaf (src/func_80074478.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: D_8009568C */

void func_80074478(int index, int value) {
    if (value != D_8009568C[index]) {
        D_8009568C[index] = value;
    }
}

