/*
 * decomp-source: func_8008F178
 * matched VMA 0x8008F178  file 0x7F978  span 0x38 bytes / 14 words
 * evidence: docs/evidence/func_8008F178/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8008F178.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
/* boundary: func_8008F0D0 has no pc_port implementation yet */
#define func_8008F0D0(...) PE_D_COMP_BOUNDARY3("func_8008F0D0", 0x8008F0D0u, __VA_ARGS__)

void func_8008F178(pe_addr_t pe_a0, int a1)
{
    unsigned char *host_D_800B2900 = PE_DECOMP_ARRAY(0x800B2900u, unsigned char);
    unsigned char *host_a0 = (unsigned char *)PE_Translate(pe_a0, 1);
    /* verbatim body (src/func_8008F178.c) */

    unsigned char *p = host_D_800B2900 + (a1 << 6);
    *(short *)(host_a0 + 0x5A) = (short)a1;
    func_8008F0D0( pe_a0, p, *(int *)p);

}
