/*
 * decomp-source: func_80086DAC
 * matched VMA 0x80086DAC  file 0x775AC  span 0x38 bytes / 14 words
 * evidence: docs/evidence/func_80086DAC/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80086DAC.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_800BCD80 PE_DECOMP_SCALAR(0x800BCD80u, int)
#define D_800BCD84 PE_DECOMP_SCALAR(0x800BCD84u, int)

/* ── verbatim matching leaf (src/func_80086DAC.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: D_800BCD80, D_800BCD84 */
/* shimmed by pe_guest_decomp.h: func_8008CBA8 */
void func_80086DAC(int a0) { D_800BCD80 = 0xD0; D_800BCD84 = a0 & 0xFF; func_8008CBA8(); }

