/*
 * decomp-source: func_800528C4
 * matched VMA 0x800528C4  file 0x430C4  span 0x2C bytes / 11 words
 * evidence: docs/evidence/func_800528C4/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_800528C4.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_800A76A4 PE_DECOMP_ARRAY(0x800A76A4u, int)

/* ── verbatim matching leaf (src/func_800528C4.c) ───────────────────────── */

/* shimmed by pe_guest_decomp.h: D_800A76A4 */
void func_800528C4(int a0, int a1) {
    D_800A76A4[a0 * 3] = a1 * 60;
}

