/*
 * decomp-source: func_8007DD74
 * matched VMA 0x8007DD74  file 0x6E574  span 0x34 bytes / 13 words
 * evidence: docs/evidence/func_8007DD74/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8007DD74.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
/* boundary: func_8007DDB4 has no pc_port implementation yet */
#define func_8007DDB4(...) PE_D_COMP_BOUNDARY3("func_8007DDB4", 0x8007DDB4u, __VA_ARGS__)

/* boundary: func_8007DDC4 has no pc_port implementation yet */
#define func_8007DDC4(...) PE_D_COMP_BOUNDARY1("func_8007DDC4", 0x8007DDC4u, __VA_ARGS__)

void func_8007DD74(pe_addr_t pe_a0)
{
    /* verbatim body (src/func_8007DD74.c) */

    func_8007DDC4( pe_a0);
    func_8007DDB4( pe_a0, 0x3F, 0);

}
