/*
 * decomp-source: func_80042BEC
 * matched VMA 0x80042BEC  file 0x333EC  span 0x14 bytes / 5 words
 * evidence: docs/evidence/func_80042BEC/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80042BEC.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_800A1824 PE_DECOMP_SCALAR(0x800A1824u, unsigned int)

/* ── verbatim matching leaf (src/func_80042BEC.c) ───────────────────────── */

/* Opaque-word setter (Stage 3 batch): set D_800A1824 = 1, return 0.
 * VRAM 0x80042BEC / file 0x333EC / size 0x14.
 * Era path: gcc-2.7.2-psx -O2 -G0 + maspsx 2.21 --dont-expand-li.
 *
 * Type provenance (lead opaque-word ruling): every writer/reader of
 * D_800A1824 is bare 32-bit sw/lw. Typed unsigned int (u32); refine if a
 * narrowing reader is later found. Pilot proof: func_80042C28 matched.
 */
/* shimmed by pe_guest_decomp.h: D_800A1824 */

int func_80042BEC(void) {
    D_800A1824 = 1;
    return 0;
}

