/*
 * decomp-source: func_80080940
 * matched VMA 0x80080940  file 0x71140  span 0x10 bytes / 4 words
 * evidence: docs/evidence/func_80080940/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80080940.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009B554 PE_DECOMP_SCALAR(0x8009B554u, int)

/* ── verbatim matching leaf (src/func_80080940.c) ───────────────────────── */

/* Phase 5BB: fifty-first matching C leaf (mid-704BC carve).
 * VRAM 0x80080940 / file 0x71140 / size 0x10.
 * Original: lui $v0,%hi(D_8009B554); lw $v0,%lo(D_8009B554)($v0);
 *           jr $ra; nop
 * 32-bit global getter; plain Phase 4J -O1 emits the exact four words.
 */
/* shimmed by pe_guest_decomp.h: D_8009B554 */

int func_80080940(void) {
    return D_8009B554;
}

