/*
 * decomp-source: func_80076B58
 * matched VMA 0x80076B58  file 0x67358  span 0x40 bytes / 16 words
 * evidence: docs/evidence/func_80076B58/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80076B58.c — do not
 * edit by hand; the matching leaf is the authority.  Pointer parameters
 * are adapted from host pointers to guest addresses (`pe_addr_t`); the
 * function body is otherwise verbatim.  See
 * docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */
#include "pe_guest_decomp.h"
int func_80076B58(pe_addr_t pe_a0, int a1)
{
    int *host_D_80095854 = PE_DECOMP_PTRGLOBAL(0x80095854u, int);
    int *host_D_80095850 = PE_DECOMP_PTRGLOBAL(0x80095850u, int);
    int *host_a0 = (int *)PE_Translate(pe_a0, 1);
    /* verbatim body (src/func_80076B58.c) */

    int a2 = a1 - 1;
    *host_D_80095854 = 0x04000000;
    if (a1 != 0) {
        do {
            int v = *host_a0;
            host_a0++;
            *host_D_80095850 = v;
            a2--;
        } while (a2 != -1);
    }
    return 0;

}
