/*
 * decomp-source: func_8003D82C
 * matched VMA 0x8003D82C  file 0x2E02C  span 0x8 bytes / 2 words
 * evidence: docs/evidence/func_8003D82C/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8003D82C.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

/* ── verbatim matching leaf (src/func_8003D82C.c) ───────────────────────── */

/* Phase 5AJ: thirty-second matching C leaf (mid-2A0C carve).
 * VRAM 0x8003D82C / file 0x2E02C / size 0x8.
 * Original: jr $ra; addiu $v0,$zero,1 — return-1 stub (li in delay slot).
 * First of the seven byte-identical return-1 twins (2026-07-09 triage).
 * Scratch probe: GCC 14.2 Phase 4J flags exact 0x8-byte match.
 */
int func_8003D82C(void) {
    return 1;
}

