/*
 * decomp-source: func_8004D288
 * matched VMA 0x8004D288  file 0x3DA88  span 0x10 bytes / 4 words
 * evidence: docs/evidence/func_8004D288/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8004D288.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009CFF8 PE_DECOMP_SCALAR(0x8009CFF8u, int)

/* ── verbatim matching leaf (src/func_8004D288.c) ───────────────────────── */

/* Phase 5DD: gp-relative setter func_8004D288 (-G 8 -fno-delayed-branch).
 * gp base 0x8009CD70; R_MIPS_GPREL16 + _gp resolve to retail offset. */
/* shimmed by pe_guest_decomp.h: D_8009CFF8 */
void func_8004D288(void){ D_8009CFF8 = 1; }

