/*
 * decomp-source: func_8007DC84
 * matched VMA 0x8007DC84  file 0x6E484  span 0x28 bytes / 10 words
 * evidence: docs/evidence/func_8007DC84/REPORT.md
 *
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_8007DC84.c — do not
 * edit by hand; the matching leaf is the authority.  The body is copied
 * verbatim; only the host adaptation (guest-RAM data symbols + loud
 * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.
 */

#include "pe_guest_decomp.h"

#define D_8009B410 PE_DECOMP_PTRGLOBAL(0x8009B410u, unsigned int)

/* ── verbatim matching leaf (src/func_8007DC84.c) ───────────────────────── */

/* VRAM 0x8007DC84 / file 0x6E484 / size 0x28.
 * RMW: clear bits 24-27 of the word at the pointer global, set 0x22000000. */
/* shimmed by pe_guest_decomp.h: D_8009B410 */

void func_8007DC84(void) {
    *D_8009B410 = (*D_8009B410 & 0xF0FFFFFFu) | 0x22000000u;
}

