#!/usr/bin/env python3
"""Original field item awards, pickup windows, input and complete draw graphs."""
import hashlib
import struct
import sys
from pe_battle_hud_oracle import ROOT, execute
from pe_inventory_entry_oracle import fixture as menu_fixture, RANGES
from pe_scripted_exit_oracle import words

ENTRIES=(0x800532B4,0x800194B0,0x8004F490,0x80015BAC,0x8004F644,
         0x8004F730,0x8004F798,0x8004F7D8,0x80062FEC,0x8005E30C)
RESULT_ENTRIES={0,1,3,5}
CASES=[]
for item in (0,1,200,255,256,383,384,511,512,520,521,0xFFFFFFFF):
    CASES.append(dict(entry=0,item=item))
for item in (1,6,200,256):
    for full in (0,1):CASES.append(dict(entry=1,item=item,full=full))
for kind in (1,9,10,15):
    for bank in (0,1):
        CASES.append(dict(entry=2,kind=kind,bank=bank))
        CASES.append(dict(entry=8,kind=kind,bank=bank))
for kind in (1,9):
    for bank in (0,1):CASES.append(dict(entry=8,kind=kind,bank=bank,slots=3))
for flags in (0,32):
    for overlay in (0,0x1000):
        for kind in (1,10):CASES.append(dict(entry=3,flags=flags,overlay=overlay,kind=kind))
for entry in (4,6,7):
    for bank in (0,1):CASES.append(dict(entry=entry,bank=bank))
for event in (0,2,64,0x10000,0x10040):
    for special in (0,1):
        CASES.append(dict(entry=5,event=event,special=special))
        CASES.append(dict(entry=9,event=event,special=special))


def fixture(exe,c):
    r,s,_=menu_fixture(exe,dict(entry=3,bank=c.get('bank',0)))
    def put(a,b):a&=0x1FFFFF;r[a:a+len(b)]=b;s[a:a+len(b)]=b
    def sw(a,v):put(a,struct.pack('<I',v&0xFFFFFFFF))
    def sh(a,v):put(a,struct.pack('<H',v&65535))
    def sb(a,v):put(a,bytes((v&255,)))
    def word(a):return struct.unpack_from('<I',r,a&0x1FFFFF)[0]
    item=c.get('item',200);kind=c.get('kind',10)
    sw(0x142000,0x80142020);sw(0x142004,0x80142024);sw(0x142020,item);sw(0x142024,0xDEADBEEF)
    sw(0x9D300,0x80142100);sw(0x142108,c.get('flags',0));sw(0x142110,77)
    sw(0x9CE00,0x80143000);sw(0xB0CD8,c.get('overlay',0));sw(0x9D1A0,0x4040)
    record=0x154000+199*32
    sb(record+6,kind);sb(record+20,c.get('slots',0))
    sb(record+21,0);sb(record+22,1);sb(record+23,31)
    for offset,value in ((7,32),(8,27),(9,14)):sb(record+offset,value)
    for offset,value in ((14,-3),(16,4),(18,13)):sh(record+offset,value)
    sw(0x9CF58,0x80000000+record);sw(0x9CF38,c.get('special',0))
    if c.get('full'):
        for i in range(word(0x9D050)):sh(word(0x9D048)+i*2,6)
    window=0
    if c['entry'] in (5,8,9):
        execute(r,0x8004F490,(item,))
        window=word(0x9D154)
        while word(window+36)==19:window=word(window)
    if c['entry']==9:
        q=0x80140500;sw(q,0);sw(q+4,1);sw(q+8,c['event'])
        sw(0x9D0E0,q);sw(0x9D0E4,q);sw(0x9D0EC,1)
    args=((item,),(0x80142000,),(item,),(0x80142000,),(),
          (window,c.get('event',0)),(),(),(),())[c['entry']]
    for a,n in RANGES:s[a:a+n]=r[a:a+n]
    return r,s,args


def fingerprint(r):
    h=14695981039346656037
    for a,n in RANGES:
        for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
    return h


def main():
    exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
    assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    _,s,_=fixture(exe,CASES[0]);base=words(s);common=[(i*4,v) for i,v in enumerate(base) if v]
    patches=[];cases=[]
    for k,c in enumerate(CASES):
        r,s,args=fixture(exe,c);first=len(patches)
        patches.extend((i*4,v) for i,(v,b) in enumerate(zip(words(s),base)) if v!=b)
        regs=execute(r,ENTRIES[c['entry']],args,instruction_budget=900000)
        result=regs[2] if c['entry'] in RESULT_ENTRIES else 0;h=fingerprint(r)
        cases.append((c['entry'],first,len(patches),args,result,h))
        print(k,c,hex(result),hex(h),flush=True)
        if '--dump' in sys.argv:(ROOT/f'local/live/pickup-oracle-{k}.bin').write_bytes(r)
    out=['/* Generated by pe_field_pickup_oracle.py; original instruction execution. */']
    for name,rows in (('ranges',RANGES),('common',common),('patches',patches)):
        out.append(f'static const uint32_t SEW17_{name}[][2]={{')
        out.extend(f'    {{0x{a:X}u,0x{b:X}u}},' for a,b in rows);out.append('};')
    out.append('static const struct { unsigned entry,first,end; uint32_t args[2],result; uint64_t hash; } SEW17_cases[]={')
    for e,a,b,args,result,h in cases:
        params=','.join(f'0x{x:08X}u' for x in args) or '0'
        out.append(f'    {{{e},{a},{b},{{{params}}},0x{result:08X}u,UINT64_C(0x{h:016X})}},')
    out.append('};')
    if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_field_pickup_cases.h').write_text('\n'.join(out)+'\n')
    print('PASS:',len(cases),'complete original field pickup cases')


if __name__=='__main__':main()
