#!/usr/bin/env python3
"""Turn the m2c skeleton for func_8001D340 into a compiling width-typed file.

Usage:  python3 type_m2c.py <m2c_draft.c> <out.c> [--phantom 0x2B8]

Each `BASE->unkNN` becomes a width-correct absolute access macro
(RB/RH/RW/RS/RSW/RP).  Field widths were read directly from the retail
load/store opcodes of `asm/disc1/DB40.s`; the mapping is below.  The optional
`--phantom` inserts an address-taken dead local of that size just before the
first statement, so cc1 emits retail's 0x328 frame (0x310 bytes of never-accessed
local space).  0x2B8 yields `vars=760, regs=5, args=24` -> frame 0x328.
"""
from __future__ import annotations

import argparse
import re
import sys

REC = {
    'unk8': 'RSW', 'unkC': 'RH', 'unkE': 'RH', 'unk10': 'RH', 'unk12': 'RB',
    'unk1C': 'RS', 'unk24': 'RH', 'unk28': 'RSW', 'unk2C': 'RSW',
    'unk30': 'RSW', 'unk34': 'RSW', 'unk48': 'RB', 'unk49': 'RB',
    'unk4A': 'RH', 'unk4C': 'RW', 'unk50': 'RS', 'unk52': 'RH', 'unk54': 'RH',
    'unk56': 'RB', 'unk57': 'RB', 'unk58': 'RS', 'unk5A': 'RH', 'unk5C': 'RS',
    'unk5E': 'RB', 'unk5F': 'RB', 'unk66': 'RB', 'unk6C': 'RP',
}
ACT = {
    'unkE': 'RB', 'unk28': 'RSW', 'unk2A': 'RS', 'unk2E': 'RS', 'unk30': 'RSW',
    'unk32': 'RS', 'unk40': 'RSW', 'unk48': 'RSW', 'unk68': 'RSW',
    'unk6C': 'RSW', 'unk70': 'RSW', 'unk98': 'RSW', 'unk210': 'RH', 'unk212': 'RH',
}
NODE = {'unk0': 'RSW', 'unk10': 'RSW', 'unk18': 'RP', 'unk92': 'RB',
        'unk93': 'RB', 'unk9C': 'RH'}
ENEMY = {'unk0': 'RP', 'unk4': 'RP', 'unk98': 'RW', 'unk268': 'RS',
         'unk26A': 'RS', 'unk26C': 'RS'}
MAPS = {'D_8009D278': REC, 'D_8009D254': ACT, 'temp_a1_2': REC,
        'temp_v1_6': NODE, 'var_s0': ENEMY}

HEADER = r'''/* Typed compile of the m2c skeleton for func_8001D340 (0xDB40, 0x2194).
 * EVIDENCE ONLY -- not a registered match.  Generated by type_m2c.py.
 */
typedef unsigned char  u8;
typedef unsigned short u16;
typedef unsigned int   u32;
typedef signed char    s8;
typedef short          s16;
typedef int            s32;
#ifndef NULL
#define NULL 0
#endif

#define RB(b,o)   (*(u8  *)((u8 *)(b) + (o)))
#define RH(b,o)   (*(u16 *)((u8 *)(b) + (o)))
#define RW(b,o)   (*(u32 *)((u8 *)(b) + (o)))
#define RS(b,o)   (*(s16 *)((u8 *)(b) + (o)))
#define RSW(b,o)  (*(s32 *)((u8 *)(b) + (o)))
#define RP(b,o)   (*(void **)((u8 *)(b) + (o)))
#define W16(b,o)  (*(u16 *)((u8 *)(b) + (o)))

extern u8 *D_8009D278;
extern u8 *D_8009D254;
extern u8 *D_8009D20C;
extern u32 D_8009CDDC, D_8009D1A0, D_8009D1AC, D_8009D1E8, D_8009D200;
extern u32 D_8009D28C, D_8009D2E8, D_8009D2FC, D_800B0E08, D_800BCF88;
extern u8  D_8009D1CE, D_8009D1D4, D_8009D234, D_8009D244;
extern u8  D_800B692C, D_800B692D, D_800B692E, D_800B6948, D_800B6949, D_800B694A;
'''

SCALARS = ('D_8009CDDC', 'D_8009D1A0', 'D_8009D1AC', 'D_8009D1E8',
           'D_8009D200', 'D_8009D28C', 'D_8009D2E8', 'D_8009D2FC',
           'D_800B0E08', 'D_800BCF88', 'D_8009D1CE', 'D_8009D1D4',
           'D_8009D234', 'D_8009D244', 'D_800B692C', 'D_800B692D',
           'D_800B692E', 'D_800B6948', 'D_800B6949', 'D_800B694A',
           'D_8009D278', 'D_8009D254', 'D_8009D20C')


def transform(text: str, phantom: int | None) -> str:
    text = text.split('\n', 1)[1]  # drop m2c's leading comment line
    text = text.replace(
        '((temp_v1_8 * 2) + temp_v1_6)->unkB6',
        'RW((u8*)((temp_v1_8 * 2) + temp_v1_6),0xB6)')
    text = text.replace('var_v0 = (s16) D_8009D278;\n        var_v0->unkC = 0;',
                        'W16(D_8009D278, 0xC) = 0;')

    def repl(m: re.Match[str]) -> str:
        base, field = m.group(1), m.group(2)
        macro = MAPS[base][field]
        return '%s(%s,0x%s)' % (macro, base, field[3:])

    text = re.sub(r'\b(D_8009D278|D_8009D254|temp_a1_2|temp_v1_6|var_s0)'
                  r'\s*->\s*(unk[0-9A-Fa-f]+)', repl, text)
    text = text.replace('RP(D_8009D278,0x6C)->unk4',
                        'RW(RP(D_8009D278,0x6C),0x4)')
    text = (text.replace('saved_reg_gp->unkC0', '*(s8*)0x8009CE30')
                .replace('saved_reg_gp->unkC4', '*(s8*)0x8009CE34'))

    if phantom is not None:
        marker = '    temp_s2 = D_8009D278 + 0x4C;'
        text = text.replace(
            marker, '    u8 phantom[%d]; (void)phantom;\n%s' % (phantom, marker), 1)

    colors = {c for c in re.findall(r'\bD_800B0[0-9A-Fa-f]{3}\b', text)
              if c not in SCALARS and c != 'D_800B0E08'}
    header = HEADER
    for symbol in sorted(colors):
        header += 'extern u8 %s;\n' % symbol
    return header + '\n' + text


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('source')
    ap.add_argument('output')
    ap.add_argument('--phantom', type=lambda s: int(s, 0), default=None)
    args = ap.parse_args()
    with open(args.source) as stream:
        text = stream.read()
    with open(args.output, 'w') as stream:
        stream.write(transform(text, args.phantom))
    return 0


if __name__ == '__main__':
    sys.exit(main())
