/* Generated by pe_gte_rt_leaves_oracle.py; original EXE execution. */
static const uint32_t DAY1_gte_rt_ranges[][2]={
    {0x140000u,0x20u},
    {0x141000u,0x10u},
    {0x141020u,0x18u},
};
static const uint32_t DAY1_gte_rt_common[][2]={
    {0x140000u,0x1000u},
    {0x140008u,0x1000u},
    {0x140010u,0x1000u},
    {0x14001Cu,0xC8u},
    {0x141020u,0x50u},
    {0x141024u,0x28u},
    {0x141028u,0x140000u},
    {0x14102Cu,0x28u},
    {0x141030u,0xFFD8u},
    {0x141034u,0x28u},
};
static const uint32_t DAY1_gte_rt_patches[][2]={
    {0x140000u,0x801000u},
    {0x140014u,0xAu},
    {0x140018u,0xFFFFFFECu},
    {0x14001Cu,0x190u},
    {0x140000u,0xF000u},
    {0x14001Cu,0x50u},
};
static const struct { unsigned first,end; uint32_t ret; uint64_t hash; } DAY1_gte_rt_cases[]={
    {0,0,0x0u,UINT64_C(0x72CC52DB4F5762AC)},
    {0,4,0x0u,UINT64_C(0xF96B7C7D011B0E2E)},
    {4,6,0x0u,UINT64_C(0x9D38561F3FA9F9E4)},
};
