/* CD command wrapper: select command and issue via func_8008CBA8.
 * VRAM 0x80086A28 / file 0x77228 / size 0x58.
 * Generated by tools/analysis/gen_cd_wrappers.py from the disassembly. */
extern unsigned int D_800BCD80;
extern unsigned int D_800BCD84;
extern unsigned int D_800BCD88;
extern unsigned int D_800BCD8C;
extern unsigned int D_800BCD90;
extern void func_8008CBA8(void);

void func_80086A28(unsigned int a0, unsigned int a1, unsigned int a2) {
    D_800BCD80 = 0xA2;
    D_800BCD84 = a0 & 0x3FF;
    D_800BCD88 = a1 & 0xFFFFFF;
    D_800BCD8C = a2 & 0xFF;
    func_8008CBA8();
}
