/* CD command wrapper: select command and issue via func_8008CBA8.
 * VRAM 0x8008682C / file 0x7702C / size 0x48.
 * Generated by tools/analysis/gen_cd_wrappers.py from the disassembly. */
extern unsigned int D_800BCD80;
extern unsigned int D_800BCD84;
extern unsigned int D_800BCD88;
extern unsigned int D_800BCD8C;
extern unsigned int D_800BCD90;
extern void func_8008CBA8(void);

void func_8008682C(unsigned int a0) {
    unsigned int v0;

    switch (a0) {
    case 1:
        v0 = 0x9A;
        break;
    case 2:
        v0 = 0x9C;
        break;
    default:
        v0 = 0x98;
        break;
    }
    D_800BCD80 = v0;
    func_8008CBA8();
}
