/* CD command wrapper: select command and issue via func_8008CBA8.
 * VRAM 0x80086568 / file 0x76D68 / size 0x3C.
 * Generated by tools/analysis/gen_cd_wrappers.py from the disassembly. */
extern unsigned int D_800BCD80;
extern unsigned int D_800BCD84;
extern unsigned int D_800BCD88;
extern unsigned int D_800BCD8C;
extern unsigned int D_800BCD90;
extern void func_8008CBA8(void);

void func_80086568(unsigned int a0, unsigned int a1) {
    D_800BCD80 = 0x12;
    D_800BCD84 = a0;
    D_800BCD88 = a1;
    func_8008CBA8();
}
