/* CD command wrapper: select command and issue via func_8008CBA8.
 * VRAM 0x800868F0 / file 0x770F0 / size 0x58.
 * Generated by tools/analysis/gen_cd_wrappers.py from the disassembly. */
extern unsigned int D_800BCD80;
extern unsigned int D_800BCD84;
extern unsigned int D_800BCD88;
extern unsigned int D_800BCD8C;
extern unsigned int D_800BCD90;
extern void func_8008CBA8(void);

void func_800868F0(unsigned int a0, unsigned int a1, unsigned int a2) {
    D_800BCD80 = 0xA0;
    D_800BCD84 = a0 & 0xFFFF;
    D_800BCD88 = a1 & 0xFFFFFF;
    D_800BCD8C = a2 & 0x7F;
    func_8008CBA8();
}
