/* CD command wrapper: select command and issue via func_8008CBA8.
 * VRAM 0x80086B1C / file 0x7731C / size 0x44.
 * Generated by tools/analysis/gen_cd_wrappers.py from the disassembly. */
extern unsigned int D_800BCD80;
extern unsigned int D_800BCD84;
extern unsigned int D_800BCD88;
extern unsigned int D_800BCD8C;
extern unsigned int D_800BCD90;
extern void func_8008CBA8(void);

void func_80086B1C(unsigned int a0, unsigned int a1) {
    D_800BCD80 = 0xAD;
    D_800BCD84 = a0 & 0xFF;
    D_800BCD88 = a1 & 0xFF;
    func_8008CBA8();
}
