/* CD command wrapper: select command and issue via func_8008CBA8.
 * VRAM 0x80086A80 / file 0x77280 / size 0x64.
 * Generated by tools/analysis/gen_cd_wrappers.py from the disassembly. */
extern unsigned int D_800BCD80;
extern unsigned int D_800BCD84;
extern unsigned int D_800BCD88;
extern unsigned int D_800BCD8C;
extern unsigned int D_800BCD90;
extern void func_8008CBA8(void);

void func_80086A80(unsigned int a0, unsigned int a1, unsigned int a2, unsigned int a3) {
    D_800BCD80 = 0xA3;
    D_800BCD84 = a0 & 0x3FF;
    D_800BCD88 = a1 & 0xFFFFFF;
    D_800BCD8C = a2 & 0xFF;
    D_800BCD90 = a3 & 0xFF;
    func_8008CBA8();
}
