/* CD command wrapper: select command and issue via func_8008CBA8.
 * VRAM 0x800867B0 / file 0x76FB0 / size 0x34.
 * Generated by tools/analysis/gen_cd_wrappers.py from the disassembly. */
extern unsigned int D_800BCD80;
extern unsigned int D_800BCD84;
extern unsigned int D_800BCD88;
extern unsigned int D_800BCD8C;
extern unsigned int D_800BCD90;
extern void func_8008CBA8(void);

void func_800867B0(unsigned int a0) {
    D_800BCD80 = 0x92;
    D_800BCD84 = a0;
    func_8008CBA8();
}
