/* CD command wrapper: select command and issue via func_8008CBA8.
 * VRAM 0x800866A4 / file 0x76EA4 / size 0x4C.
 * Generated by tools/analysis/gen_cd_wrappers.py from the disassembly. */
extern unsigned int D_800BCD80;
extern unsigned int D_800BCD84;
extern unsigned int D_800BCD88;
extern unsigned int D_800BCD8C;
extern unsigned int D_800BCD90;
extern void func_8008CBA8(void);

void func_800866A4(unsigned int a0, unsigned int a1) {
    D_800BCD80 = 0x21;
    D_800BCD84 = a0 & 0xFFFF;
    D_800BCD88 = a1 & 0xFFFFFF;
    func_8008CBA8();
}
