/* CD command wrapper: select command and issue via func_8008CBA8.
 * VRAM 0x80087024 / file 0x77824 / size 0x2C.
 * Generated by tools/analysis/gen_cd_wrappers.py from the disassembly. */
extern unsigned int D_800BCD80;
extern unsigned int D_800BCD84;
extern unsigned int D_800BCD88;
extern unsigned int D_800BCD8C;
extern unsigned int D_800BCD90;
extern void func_8008CBA8(void);

void func_80087024(void) {
    D_800BCD80 = 0xF1;
    func_8008CBA8();
}
