/* CD command wrapper: select command and issue via func_8008CBA8.
 * VRAM 0x800868AC / file 0x770AC / size 0x44.
 * Generated by tools/analysis/gen_cd_wrappers.py from the disassembly. */
extern unsigned int D_800BCD80;
extern unsigned int D_800BCD84;
extern unsigned int D_800BCD88;
extern unsigned int D_800BCD8C;
extern unsigned int D_800BCD90;
extern void func_8008CBA8(void);

void func_800868AC(unsigned int a0, unsigned int a1) {
    D_800BCD80 = 0xA9;
    D_800BCD84 = a0 & 0xFF;
    D_800BCD88 = a1 & 0x7F;
    func_8008CBA8();
}
