/* CD command wrapper: select command and issue via func_8008CBA8.
 * VRAM 0x800867E4 / file 0x76FE4 / size 0x48.
 * Generated by tools/analysis/gen_cd_wrappers.py from the disassembly. */
extern unsigned int D_800BCD80;
extern unsigned int D_800BCD84;
extern unsigned int D_800BCD88;
extern unsigned int D_800BCD8C;
extern unsigned int D_800BCD90;
extern void func_8008CBA8(void);

void func_800867E4(unsigned int a0) {
    unsigned int v0;

    switch (a0) {
    case 1:
        v0 = 0x9B;
        break;
    case 2:
        v0 = 0x9D;
        break;
    default:
        v0 = 0x99;
        break;
    }
    D_800BCD80 = v0;
    func_8008CBA8();
}
