/* CD command wrapper: select command and issue via func_8008CBA8.
 * VRAM 0x80086DAC / file 0x775AC / size 0x38.
 * Generated by tools/analysis/gen_cd_wrappers.py from the disassembly. */
extern unsigned int D_800BCD80;
extern unsigned int D_800BCD84;
extern unsigned int D_800BCD88;
extern unsigned int D_800BCD8C;
extern unsigned int D_800BCD90;
extern void func_8008CBA8(void);

void func_80086DAC(unsigned int a0) {
    D_800BCD80 = 0xD0;
    D_800BCD84 = a0 & 0xFF;
    func_8008CBA8();
}
