/* CD command wrapper: select command and issue via func_8008CBA8.
 * VRAM 0x800869AC / file 0x771AC / size 0x38.
 * Generated by tools/analysis/gen_cd_wrappers.py from the disassembly. */
extern unsigned int D_800BCD80;
extern unsigned int D_800BCD84;
extern unsigned int D_800BCD88;
extern unsigned int D_800BCD8C;
extern unsigned int D_800BCD90;
extern void func_8008CBA8(void);

void func_800869AC(unsigned int a0) {
    D_800BCD80 = 0xAA;
    D_800BCD84 = a0 & 0xFF;
    func_8008CBA8();
}
