/* CD command wrapper: select command and issue via func_8008CBA8.
 * VRAM 0x80086FAC / file 0x777AC / size 0x4C.
 * Generated by tools/analysis/gen_cd_wrappers.py from the disassembly. */
extern unsigned int D_800BCD80;
extern unsigned int D_800BCD84;
extern unsigned int D_800BCD88;
extern unsigned int D_800BCD8C;
extern unsigned int D_800BCD90;
extern void func_8008CBA8(void);

void func_80086FAC(unsigned int a0, unsigned int a1, unsigned int a2) {
    D_800BCD80 = 0xDA;
    D_800BCD84 = a0;
    D_800BCD88 = a1 & 0xFF;
    D_800BCD8C = a2 & 0xFF;
    func_8008CBA8();
}
