/* CD command wrapper: select command and issue via func_8008CBA8.
 * VRAM 0x80086770 / file 0x76F70 / size 0x40.
 * Generated by tools/analysis/gen_cd_wrappers.py from the disassembly. */
extern unsigned int D_800BCD80;
extern unsigned int D_800BCD84;
extern unsigned int D_800BCD88;
extern unsigned int D_800BCD8C;
extern unsigned int D_800BCD90;
extern void func_8008CBA8(void);

void func_80086770(unsigned int a0) {
    D_800BCD80 = 0x90;
    D_800BCD84 = a0 & 0xFFFFFF;
    func_8008CBA8();
}
