/* CD command wrapper: select command and issue via func_8008CBA8.
 * VRAM 0x80086CA4 / file 0x774A4 / size 0x54.
 * Generated by tools/analysis/gen_cd_wrappers.py from the disassembly. */
extern unsigned int D_800BCD80;
extern unsigned int D_800BCD84;
extern unsigned int D_800BCD88;
extern unsigned int D_800BCD8C;
extern unsigned int D_800BCD90;
extern void func_8008CBA8(void);

void func_80086CA4(unsigned int a0, unsigned int a1, unsigned int a2, unsigned int a3) {
    D_800BCD80 = 0xC2;
    D_800BCD84 = a1;
    D_800BCD88 = a2 & 0x7F;
    D_800BCD8C = a3 & 0x7F;
    D_800BCD90 = a0;
    func_8008CBA8();
}
