#!/usr/bin/env python3
"""Rank the remaining non-matching PS1 functions as a decompilation worklist.

Reads the splat-generated assembly under asm/disc1/*.s (git-ignored, produced by
scripts/split_us.sh) and collects every `nonmatching <name>, <size>` directive
that has a matching `glabel <name>` — i.e. a real function boundary with a known
extent.  Splat also emits `nonmatching <name>` (no size) as `alabel` data
symbols in the same files; those are excluded.

The output is the work queue for "decompile to 100%": biggest functions first,
because byte coverage is dominated by a handful of large routines.

Usage:
    python3 tools/analysis/asm_function_worklist.py [--top N] [--json PATH] \
        [--md PATH] [--asm-dir DIR]

Exit status: 0 on success, 1 if no assembly was found (run split_us.sh first).
"""

from __future__ import annotations

import argparse
import glob
import json
import os
import re
import sys

NONMATCHING_RE = re.compile(r"^nonmatching\s+(\S+),\s*(0x[0-9A-Fa-f]+|\d+)\s*$")
GLABEL_RE = re.compile(r"^glabel\s+(\S+)")


def find_repo_root() -> str:
    path = os.path.abspath(os.path.dirname(__file__))
    while path != "/":
        if os.path.isfile(os.path.join(path, "CLAUDE.md")):
            return path
        path = os.path.dirname(path)
    return os.getcwd()


def collect(asm_dir: str) -> list[dict]:
    rows: list[dict] = []
    for path in sorted(glob.glob(os.path.join(asm_dir, "*.s"))):
        unit = os.path.splitext(os.path.basename(path))[0]
        pending: tuple[str, int] | None = None
        with open(path, "r", errors="ignore") as fh:
            for line in fh:
                m = NONMATCHING_RE.match(line)
                if m:
                    pending = (m.group(1), int(m.group(2), 0))
                    continue
                if pending is not None:
                    if line.strip() == "":
                        continue
                    g = GLABEL_RE.match(line)
                    if g and g.group(1) == pending[0]:
                        rows.append({"name": pending[0], "size": pending[1], "unit": unit})
                    pending = None
    return rows


def main() -> int:
    root = find_repo_root()
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--asm-dir", default=os.path.join(root, "asm", "disc1"))
    ap.add_argument("--top", type=int, default=40)
    ap.add_argument("--json", default=os.path.join(root, "build", "asm_worklist.json"))
    ap.add_argument("--md", default=None, help="also write a markdown report")
    args = ap.parse_args()

    rows = collect(args.asm_dir)
    if not rows:
        print(
            f"ERROR: no nonmatching function boundaries under {args.asm_dir}; "
            "run scripts/split_us.sh first",
            file=sys.stderr,
        )
        return 1

    rows.sort(key=lambda r: (-r["size"], r["name"]))
    total_bytes = sum(r["size"] for r in rows)
    report = {
        "asm_dir": os.path.relpath(args.asm_dir, root),
        "functions": len(rows),
        "total_bytes": total_bytes,
        "worklist": rows,
    }

    os.makedirs(os.path.dirname(args.json) or ".", exist_ok=True)
    with open(args.json, "w") as fh:
        json.dump(report, fh, indent=1)
        fh.write("\n")

    print(f"nonmatching functions with a known extent: {len(rows)}")
    print(f"total bytes: {total_bytes} (0x{total_bytes:X})")
    print(f"wrote {os.path.relpath(args.json, root)}")
    print(f"\nTop {args.top} by size:")
    for r in rows[: args.top]:
        print(f"  0x{r['size']:06X} {r['size']:6d}  {r['name']:20s} {r['unit']}.s")

    if args.md:
        with open(args.md, "w") as fh:
            fh.write("# Non-matching function worklist\n\n")
            fh.write(
                f"{len(rows)} functions with a known extent, "
                f"{total_bytes} bytes (0x{total_bytes:X}) total. "
                "Generated by `tools/analysis/asm_function_worklist.py`.\n\n"
            )
            fh.write("| bytes | hex | function | unit |\n|---:|---|---|---|\n")
            for r in rows:
                fh.write(
                    f"| {r['size']} | 0x{r['size']:X} | `{r['name']}` | {r['unit']}.s |\n"
                )
        print(f"wrote {os.path.relpath(args.md, root)}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
