#!/usr/bin/env python3
"""Generate pc_port/game/decomp/*.c host TUs from the verified matching C leaves.

Each generated TU carries one matching leaf copied verbatim from src/<name>.c
plus the host adaptation needed to run it against the pc_port guest-RAM
authority.  The matching leaf in src/ is the authority; this script never
invents or edits retail C.  Every data symbol becomes a checked guest-RAM
lvalue, and every callee pc_port has not implemented becomes a loud,
countable boundary.

Usage:
    tools/analysis/gen_decomp_ports.py              # regenerate all src-backed TUs
    tools/analysis/gen_decomp_ports.py --check      # verify, write nothing
    tools/analysis/gen_decomp_ports.py --only NAME  # one leaf (repeatable)

Exit status is non-zero if --check finds a mismatch or if a target TU has no
matching src/ leaf (an orphan that cannot be reproduced from authority).

The generated set is the set of existing pc_port/game/decomp/<name>_port.c
files: the selection of which leaves to port is a project decision, not a
property of the leaf, so this script reproduces the existing set rather than
inventing a new one.
"""
import argparse
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DECOMP_DIR = os.path.join(REPO, "pc_port", "game", "decomp")
SRC_DIR = os.path.join(REPO, "src")
CONFIG = os.path.join(REPO, "configs", "USA", "disc1.yaml")
ORPHANS_FILE = os.path.join(REPO, "tools", "analysis", "decomp_port_orphans.txt")

MARKER_PREFIX = "/* ── verbatim matching leaf (src/"
MARKER_WIDTH = 79  # total columns of the marker line, including delimiters

# A matching leaf may pin a local to a MIPS register for byte-exact codegen
# (`register int v0 asm("$2");`).  That is meaningless — and a compile error —
# on the host, where the register names do not exist.  The binding is a codegen
# lever only, so it is rewritten as the equivalent plain local declaration; the
# variable keeps identical value semantics.
REG_ASM_RE = re.compile(
    r'^(?P<indent>\s*)register\s+(?P<type>[\w\s\*]+?)\s*'
    r'(?P<name>\w+)\s+asm\s*\(\s*"\$[0-9]+"\s*\)\s*;\s*$'
)
REG_ASM_NOTE = "/* host: MIPS register binding dropped */"

HEADER_FROM = "GENERATED by tools/analysis/gen_decomp_ports.py from src/%s.c — do not"
HEADER_LEAF_TAIL = (
    " * edit by hand; the matching leaf is the authority.  The body is copied\n"
    " * verbatim; only the host adaptation (guest-RAM data symbols + loud\n"
    " * boundaries) is generated.  See docs/ai_context/PC_PORT_FROM_DECOMP.md.\n"
)
HEADER_PTR_TAIL = (
    " * edit by hand; the matching leaf is the authority.  Pointer parameters\n"
    " * are adapted from host pointers to guest addresses (`pe_addr_t`); the\n"
    " * function body is otherwise verbatim.  See\n"
    " * docs/ai_context/PC_PORT_FROM_DECOMP.md.\n"
)

DATA_DECL_RE = re.compile(
    r"^\s*extern\s+(?P<type>.+?)\s*\b(?P<names>D_[0-9A-Fa-f]{8}"
    r"(?:\s*,\s*D_[0-9A-Fa-f]{8})*)\s*(?P<array>\[\s*\])?\s*;\s*$"
)
PROTO_RE = re.compile(
    r"^(?:extern\s+)?[A-Za-z_][A-Za-z0-9_ \t\*]*?"
    r"\b(?P<name>func_[0-9A-Fa-f]{8})\s*\([^;{}]*\)\s*;\s*$"
)
CALL_RE = re.compile(r"\b(?P<name>func_[0-9A-Fa-f]{8})\s*\(")
SYM_RE = re.compile(r"\b(?P<name>D_[0-9A-Fa-f]{8})\b")


def sym_addr(name):
    """0x80017E9C from func_80017E9C / D_8009CF44."""
    return name[name.index("_") + 1:].upper()


_HEADER_MACROS = None
_HOST_DECLARED = None


def host_declared_symbols():
    """Callee names the pc_port headers already declare.

    When a leaf's own prototype for an implemented callee conflicts with the
    host declaration (the src leaf often types registers differently from the
    host port), the generated TU drops the prototype and relies on the header.
    Only a callee with no host declaration keeps its verbatim prototype.
    """
    global _HOST_DECLARED
    if _HOST_DECLARED is None:
        found = set()
        pat = re.compile(
            r"^\s*(?:extern\s+)?[A-Za-z_][A-Za-z0-9_ \t\*]*?"
            r"\b(func_[0-9A-Fa-f]{8})\s*\(",
            re.MULTILINE,
        )
        for root, dirs, files in os.walk(os.path.join(REPO, "pc_port")):
            parts = root.split(os.sep)
            if "build" in parts or "tests" in parts:
                continue
            for fn in files:
                if not fn.endswith(".h"):
                    continue
                try:
                    text = open(os.path.join(root, fn), encoding="utf-8",
                                errors="replace").read()
                except OSError:
                    continue
                found.update(pat.findall(text))
        _HOST_DECLARED = found
    return _HOST_DECLARED


def read_orphan_manifest():
    """The checked-in orphan allowlist (comments and blanks ignored)."""
    if not os.path.exists(ORPHANS_FILE):
        return set()
    out = set()
    for line in open(ORPHANS_FILE, encoding="utf-8"):
        line = line.strip()
        if line and not line.startswith("#"):
            out.add(line)
    return out


def header_macros():
    """Data-symbol names already macro-defined by the shim headers.

    A generated `#define D_XXXXXXXX ...` would otherwise be a redefinition
    error because psx_compat.h already defines some of these slots.
    """
    global _HEADER_MACROS
    if _HEADER_MACROS is None:
        found = set()
        include_dir = os.path.join(REPO, "pc_port", "include")
        for fn in os.listdir(include_dir):
            if not fn.endswith(".h"):
                continue
            for line in open(os.path.join(include_dir, fn), encoding="utf-8"):
                m = re.match(r"\s*#\s*define\s+(D_[0-9A-Fa-f]{8})\b", line)
                if m:
                    found.add(m.group(1))
        _HEADER_MACROS = found
    return _HEADER_MACROS


# ── config / metadata ────────────────────────────────────────────────────

def parse_subsegments(path):
    """Return [(offset, kind, name_or_None)] in file order.

    Every subsegment kind counts for span arithmetic: a leaf's size is the
    distance to the next subsegment of *any* kind (the next entry is often
    `rodata` or `asm`, not another `c`).
    """
    out = []
    pat = re.compile(
        r"-\s*\[\s*(0x[0-9A-Fa-f]+)\s*,\s*([A-Za-z_][A-Za-z0-9_]*)"
        r"\s*(?:,\s*([A-Za-z0-9_]+)\s*)?\]"
    )
    for line in open(path, encoding="utf-8"):
        m = pat.search(line)
        if m:
            off = int(m.group(1), 16)
            kind = m.group(2)
            out.append((off, kind, m.group(3)))
    return out


def build_meta(entries):
    """name -> dict(vma, file, span, words) for c entries with a next entry."""
    meta = {}
    for i, (off, kind, name) in enumerate(entries):
        if kind != "c" or not name:
            continue
        if i + 1 >= len(entries):
            continue
        span = entries[i + 1][0] - off
        vma = 0x80010000 + off - 0x800
        if ("func_%08X" % vma) != name:
            raise SystemExit(
                "config VMA mismatch for %s: offset 0x%X -> 0x%08X" % (name, off, vma)
            )
        meta[name] = dict(vma=vma, file=off, span=span, words=span // 4)
    return meta


# ── implemented-symbol set ───────────────────────────────────────────────

def collect_defined_symbols():
    """Names of functions with a real definition somewhere under pc_port/.

    A `#define name(...) PE_D_COMP_BOUNDARY...` is NOT a definition.  Only a
    top-level function body counts.  Build directories and the generated
    decomp TUs are included: a generated leaf really does define its function.
    """
    defined = set()
    head_re = re.compile(
        r"^(?:static\s+)?[A-Za-z_][A-Za-z0-9_ \t\*]*?"
        r"\b(func_[0-9A-Fa-f]{8})\s*\(",
        re.MULTILINE,
    )
    for root, dirs, files in os.walk(os.path.join(REPO, "pc_port")):
        if "build" in root.split(os.sep):
            continue
        for fn in files:
            if not fn.endswith(".c"):
                continue
            path = os.path.join(root, fn)
            try:
                text = open(path, encoding="utf-8", errors="replace").read()
            except OSError:
                continue
            # Strip comments before scanning: a trailing comment between the
            # parameter list and the body brace (e.g. `int f(void) /* B0(50h) */`)
            # otherwise hides the definition and its callers fall back to a
            # loud boundary even though the function is implemented.
            text = re.sub(r"/\*.*?\*/", " ", text, flags=re.DOTALL)
            text = re.sub(r"//[^\n]*", " ", text)
            for m in head_re.finditer(text):
                name = m.group(1)
                i = m.end()
                depth = 1
                while i < len(text) and depth:
                    if text[i] == "(":
                        depth += 1
                    elif text[i] == ")":
                        depth -= 1
                    elif text[i] == ";" and depth == 1:
                        break
                    i += 1
                if depth != 0:
                    continue
                j = i
                while j < len(text) and text[j] in " \t\r\n":
                    j += 1
                if j < len(text) and text[j] == "{":
                    defined.add(name)
    return defined


# ── source parsing ───────────────────────────────────────────────────────

def classify_data_decl(line):
    """Return (type, kind) for an extern data decl, or None."""
    m = DATA_DECL_RE.match(line)
    if not m:
        return None
    typ = m.group("type").strip()
    if m.group("array"):
        return typ, "ARRAY"
    if typ.endswith("*"):
        return typ[:-1].strip(), "PTRGLOBAL"
    return typ, "SCALAR"


def split_declarators(names):
    return [n.strip() for n in names.split(",")]


def first_use_order(text, symbols):
    seen = []
    for m in SYM_RE.finditer(text):
        n = m.group("name")
        if n in symbols and n not in seen:
            seen.append(n)
    return seen


# ── leaf template ────────────────────────────────────────────────────────

def marker(name):
    core = "verbatim matching leaf (src/%s.c) " % name
    pre = "/* ── "
    suf = " */"
    pad = MARKER_WIDTH - len(pre) - len(core) - len(suf)
    if pad < 1:
        pad = 1
    return pre + core + "─" * pad + suf


def build_body(src_text, data_syms, boundary_callees, declared):
    """Replace data decls / boundary prototypes, rewrite boundary call args."""
    out_lines = []
    for raw in src_text.split("\n"):
        decl = classify_data_decl(raw)
        if decl is not None:
            names = split_declarators(DATA_DECL_RE.match(raw).group("names"))
            out_lines.append(
                "/* shimmed by pe_guest_decomp.h: %s */" % ", ".join(names)
            )
            continue
        m = PROTO_RE.match(raw)
        if m and (m.group("name") in boundary_callees
                  or m.group("name") in declared):
            out_lines.append(
                "/* shimmed by pe_guest_decomp.h: %s */" % m.group("name")
            )
            continue
        if REG_ASM_RE.match(raw):
            m = REG_ASM_RE.match(raw)
            out_lines.append(
                "%s%s %s %s;"
                % (m.group("indent"), m.group("type"), m.group("name"), REG_ASM_NOTE)
            )
            continue
        out_lines.append(raw)
    body = "\n".join(out_lines)
    # A data symbol passed to a callee parameter that is itself a guest
    # address is forwarded as the address (see rewrite_data_args, which keys
    # off the callee prototype or a boundary edge).  The previous blanket
    # textual rewrite of every bare first argument is gone: it turned scalar
    # value arguments such as func_80042020(D_8009CF44, ...) into the data
    # symbol's address regardless of the callee's signature.
    return rewrite_data_args(
        body, boundary_callees, collect_proto_flags(src_text), set(data_syms)
    )


def split_top_level_args(text):
    parts = []
    depth = 0
    cur = ""
    for ch in text:
        if ch in "([":
            depth += 1
        elif ch in ")]":
            depth -= 1
        if ch == "," and depth == 0:
            parts.append(cur)
            cur = ""
        else:
            cur += ch
    parts.append(cur)
    return parts


def collect_proto_flags(src_text):
    """name -> [is-pointer per parameter] from the leaf's own prototypes."""
    flags = {}
    for line in src_text.split("\n"):
        m = PROTO_RE.match(line)
        if not m:
            continue
        inside = line[line.index("(", m.start("name")) + 1:line.rindex(")")]
        out = []
        for part in split_top_level_args(inside):
            p = part.strip()
            if not p or p == "void":
                continue
            out.append("*" in p)
        flags[m.group("name")] = out
    return flags


def rewrite_data_args(body, boundary_callees, proto_flags, data_syms):
    out = []
    i = 0
    n = len(body)
    while i < n:
        if body.startswith("/*", i):
            j = body.find("*/", i + 2)
            j = n if j < 0 else j + 2
            out.append(body[i:j])
            i = j
            continue
        if body.startswith("//", i):
            j = body.find("\n", i)
            j = n if j < 0 else j
            out.append(body[i:j])
            i = j
            continue
        m = IDENT_RE.match(body, i)
        if not m:
            out.append(body[i])
            i += 1
            continue
        tok = m.group(0)
        k = m.end()
        while k < n and body[k] in " \t":
            k += 1
        if k < n and body[k] == "(" and (
            tok in proto_flags or tok in boundary_callees
        ):
            depth = 1
            a = k + 1
            cur = ""
            args = []
            while a < n and depth:
                c = body[a]
                if c == "(":
                    depth += 1
                elif c == ")":
                    depth -= 1
                    if depth == 0:
                        break
                if c == "," and depth == 1:
                    args.append(cur)
                    cur = ""
                else:
                    cur += c
                a += 1
            args.append(cur)
            flags = proto_flags.get(tok, [])
            fixed = []
            for idx, arg in enumerate(args):
                stripped = arg.strip()
                is_ptr = idx < len(flags) and flags[idx]
                first_boundary = idx == 0 and tok in boundary_callees
                if stripped in data_syms and (is_ptr or first_boundary):
                    fixed.append(
                        arg.replace(
                            stripped,
                            "(pe_addr_t)0x%su" % sym_addr(stripped),
                        )
                    )
                else:
                    fixed.append(arg)
            out.append(body[i:k + 1])
            out.append(",".join(fixed))
            out.append(")")
            i = a + 1
            continue
        out.append(tok)
        i = m.end()
    return "".join(out)


def boundary_arities(body, boundary_callees):
    arity = {}
    for m in CALL_RE.finditer(body):
        name = m.group("name")
        if name not in boundary_callees:
            continue
        i = m.end()
        depth = 1
        n = 0
        in_arg = False
        while i < len(body) and depth:
            c = body[i]
            if c == "(":
                depth += 1
                in_arg = True
            elif c == ")":
                depth -= 1
                if depth == 0:
                    if in_arg:
                        n += 1
                    break
            elif c == "," and depth == 1:
                n += 1
                in_arg = True
            elif not c.isspace():
                in_arg = True
            i += 1
        arity[name] = max(arity.get(name, 0), n)
    return arity


def generate_leaf(name, src_text, meta, defined):
    # data symbols declared in this leaf
    decls = {}  # name -> (type, kind)
    for raw in src_text.split("\n"):
        m = DATA_DECL_RE.match(raw)
        if not m:
            continue
        typ = m.group("type").strip()
        kind = "ARRAY" if m.group("array") else ("PTRGLOBAL" if typ.endswith("*") else "SCALAR")
        base = typ[:-1].strip() if kind == "PTRGLOBAL" else typ
        for n in split_declarators(m.group("names")):
            decls[n] = (base, kind)

    # callees: called in the body but not defined anywhere
    used = []
    for m in CALL_RE.finditer(src_text):
        n = m.group("name")
        if n != name and n not in used:
            used.append(n)
    boundary_callees = [n for n in used if n not in defined]

    body = build_body(src_text, list(decls), set(boundary_callees),
                      host_declared_symbols())

    data_order = first_use_order(body, set(decls))
    # keep declarations with no body use too, in declaration order
    for n in decls:
        if n not in data_order:
            data_order.append(n)

    arities = boundary_arities(body, set(boundary_callees))

    out = []
    out.append("/*\n")
    out.append(" * decomp-source: %s\n" % name)
    out.append(
        " * matched VMA 0x%X  file 0x%X  span 0x%X bytes / %d words\n"
        % (meta["vma"], meta["file"], meta["span"], meta["words"])
    )
    out.append(" * evidence: docs/evidence/%s/REPORT.md\n" % name)
    out.append(" *\n")
    out.append(" * " + (HEADER_FROM % name) + "\n")
    out.append(HEADER_LEAF_TAIL)
    out.append(" */\n")
    out.append("\n")
    out.append('#include "pe_guest_decomp.h"\n')
    out.append("\n")

    if data_order:
        for n in data_order:
            typ, kind = decls[n]
            if n in header_macros():
                out.append("#undef %s\n" % n)
            out.append(
                "#define %s PE_DECOMP_%s(0x%su, %s)\n"
                % (n, kind, sym_addr(n), typ)
            )
        out.append("\n")

    if boundary_callees:
        for n in boundary_callees:
            a = arities.get(n, 0)
            args = "" if a == 0 else ", __VA_ARGS__"
            out.append(
                "/* boundary: %s has no pc_port implementation yet */\n" % n
            )
            out.append(
                '#define %s(...) PE_D_COMP_BOUNDARY%d("%s", 0x%su%s)\n'
                % (n, a, n, sym_addr(n), args)
            )
            out.append("\n")
        out.append("\n")

    out.append(marker(name) + "\n")
    out.append("\n")
    out.append(body.rstrip("\n") + "\n\n")
    return "".join(out)


# ── pointer-parameter template ───────────────────────────────────────────

IDENT_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")


def extract_typedefs(src_text):
    """Return the verbatim top-level typedef block(s), joined.

    A leaf's struct typedefs live above its function.  We copy them verbatim;
    the host shim only needs the type name to be visible before the body.
    """
    blocks = []
    lines = src_text.split("\n")
    i = 0
    while i < len(lines):
        if lines[i].startswith("typedef"):
            depth = 0
            chunk = []
            while i < len(lines):
                line = lines[i]
                chunk.append(line)
                depth += line.count("{") - line.count("}")
                if depth <= 0 and line.rstrip().endswith(";"):
                    i += 1
                    break
                i += 1
            blocks.append("\n".join(chunk))
            continue
        i += 1
    return "\n".join(blocks)


def find_function(src_text, name):
    """Return (prefix, params_text, body_text, total_end).

    `prefix` is the declaration text from the start of its line through the
    opening paren; `total_end` is the index just past the closing brace.
    """
    m = re.search(r"\bfunc_%s\s*\(" % name[5:], src_text)
    if not m:
        return None
    # declaration starts at the beginning of the line holding the name
    line_start = src_text.rfind("\n", 0, m.start()) + 1
    prefix = src_text[line_start:m.end()]
    depth = 1
    i = m.end()
    while i < len(src_text) and depth:
        if src_text[i] == "(":
            depth += 1
        elif src_text[i] == ")":
            depth -= 1
        i += 1
    params = src_text[m.end():i - 1]
    j = i
    while j < len(src_text) and src_text[j] in " \t\r\n":
        j += 1
    if j >= len(src_text) or src_text[j] != "{":
        return None
    depth = 0
    k = j
    while k < len(src_text):
        if src_text[k] == "{":
            depth += 1
        elif src_text[k] == "}":
            depth -= 1
            if depth == 0:
                break
        k += 1
    body = src_text[j + 1:k]
    return prefix, params, body, k + 1


def parse_params(params_text):
    """Return [(type, name, is_ptr, pointee)] for a leaf's parameter list."""
    out = []
    depth = 0
    cur = ""
    parts = []
    for ch in params_text:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            parts.append(cur)
            cur = ""
        else:
            cur += ch
    if cur.strip():
        parts.append(cur)
    for part in parts:
        p = part.strip()
        if not p or p == "void":
            continue
        m = re.match(r"^(?P<type>.+?)\s*\*+\s*(?P<name>[A-Za-z_][A-Za-z0-9_]*)$", p)
        if m:
            typ = m.group("type").strip()
            out.append((typ, m.group("name"), True, typ))
        else:
            m = re.match(r"^(?P<type>.+?)\s+(?P<name>[A-Za-z_][A-Za-z0-9_]*)$", p)
            if m:
                out.append((m.group("type").strip(), m.group("name"), False, None))
            else:
                out.append((p, p, False, None))
    return out


def rewrite_ptr_body(body, params, globals_):
    """Rename params/globals and record which need host locals.

    A pointer parameter used as a *bare* call argument is forwarded as its
    guest address (`pe_name`); retail passes the address, not a translated
    host pointer.  Any other use needs a translated `host_name` local.  The
    generated file's `( pe_name` spacing for a first bare argument is an
    artefact of the original generator and is reproduced exactly.
    """
    param_names = {p[1]: p for p in params if p[2]}
    host_used = set()
    globals_used = set()
    out = []
    i = 0
    n = len(body)
    while i < n:
        if body.startswith("/*", i):
            j = body.find("*/", i + 2)
            j = n if j < 0 else j + 2
            out.append(body[i:j])
            i = j
            continue
        if body.startswith("//", i):
            j = body.find("\n", i)
            j = n if j < 0 else j
            out.append(body[i:j])
            i = j
            continue
        m = IDENT_RE.match(body, i)
        if not m:
            out.append(body[i])
            i += 1
            continue
        tok = m.group(0)
        if tok in param_names:
            prev = i - 1
            while prev >= 0 and body[prev] in " \t":
                prev -= 1
            nx = m.end()
            while nx < n and body[nx] in " \t":
                nx += 1
            bare = prev >= 0 and body[prev] in "(," and (
                nx >= n or body[nx] in ",)"
            )
            if bare:
                prefix = " " if body[prev] == "(" else ""
                out.append(prefix + "pe_" + tok)
            else:
                host_used.add(tok)
                out.append("host_" + tok)
            i = m.end()
            continue
        if tok in globals_:
            typ, kind = globals_[tok]
            globals_used.add(tok)
            if kind in ("PTRGLOBAL", "ARRAY"):
                # An array symbol decays to its base pointer, so it is bound
                # to the guest base address and used bare (host_X[i], host_X).
                out.append("host_" + tok)
            else:
                out.append("(*host_%s)" % tok)
            i = m.end()
            continue
        out.append(tok)
        i = m.end()
    return "".join(out), host_used, globals_used


def header(name, meta, ptr):
    out = []
    out.append("/*\n")
    out.append(" * decomp-source: %s\n" % name)
    out.append(
        " * matched VMA 0x%X  file 0x%X  span 0x%X bytes / %d words\n"
        % (meta["vma"], meta["file"], meta["span"], meta["words"])
    )
    out.append(" * evidence: docs/evidence/%s/REPORT.md\n" % name)
    out.append(" *\n")
    out.append(" * " + (HEADER_FROM % name) + "\n")
    out.append(HEADER_PTR_TAIL if ptr else HEADER_LEAF_TAIL)
    out.append(" */\n")
    return "".join(out)


def generate_ptr(name, src_text, meta, defined):
    fn = find_function(src_text, name)
    if fn is None:
        raise SystemExit("cannot locate function %s" % name)
    _prefix, params_text, body_text, _end = fn
    params = parse_params(params_text)

    # top-level data globals
    globals_ = {}
    for raw in src_text.split("\n"):
        m = DATA_DECL_RE.match(raw)
        if not m:
            continue
        typ = m.group("type").strip()
        kind = "ARRAY" if m.group("array") else (
            "PTRGLOBAL" if typ.endswith("*") else "SCALAR"
        )
        base = typ[:-1].strip() if kind == "PTRGLOBAL" else typ
        for gname in split_declarators(m.group("names")):
            globals_[gname] = (base, kind)

    used = []
    for m in CALL_RE.finditer(body_text):
        c = m.group("name")
        if c != name and c not in used:
            used.append(c)
    boundary_callees = [c for c in used if c not in defined]
    arities = boundary_arities(body_text, set(boundary_callees))

    typedefs = extract_typedefs(src_text)
    rewritten, host_used, globals_used = rewrite_ptr_body(body_text, params, globals_)

    out = []
    out.append(header(name, meta, ptr=True))
    out.append('#include "pe_guest_decomp.h"\n')
    if boundary_callees:
        for c in boundary_callees:
            a = arities.get(c, 0)
            args = "" if a == 0 else ", __VA_ARGS__"
            out.append("/* boundary: %s has no pc_port implementation yet */\n" % c)
            out.append(
                '#define %s(...) PE_D_COMP_BOUNDARY%d("%s", 0x%su%s)\n'
                % (c, a, c, sym_addr(c), args)
            )
        out.append("\n")
    if typedefs:
        out.append("/* verbatim leaf types */\n")
        out.append(typedefs + "\n\n")

    ret = _prefix[:-1].rstrip()
    sig = [ret, "("]
    sig_parts = []
    for typ, pname, is_ptr, _pointee in params:
        if is_ptr:
            sig_parts.append("pe_addr_t pe_%s" % pname)
        else:
            sig_parts.append("%s %s" % (typ, pname))
    sig.append(", ".join(sig_parts))
    sig.append(")\n{\n")

    body_out = []
    for gname, (typ, kind) in globals_.items():
        if gname not in globals_used:
            continue
        if kind == "PTRGLOBAL":
            body_out.append(
                "    %s *host_%s = PE_DECOMP_PTRGLOBAL(0x%su, %s);\n"
                % (typ, gname, sym_addr(gname), typ)
            )
        elif kind == "ARRAY":
            # `extern T X[];` binds to the guest array base as a T*.
            body_out.append(
                "    %s *host_%s = PE_DECOMP_PTRGLOBAL(0x%su, %s);\n"
                % (typ, gname, sym_addr(gname), typ)
            )
        elif kind == "SCALAR":
            body_out.append(
                "    %s *host_%s = &PE_DECOMP_SCALAR(0x%su, %s);\n"
                % (typ, gname, sym_addr(gname), typ)
            )
    for typ, pname, is_ptr, pointee in params:
        if is_ptr and pname in host_used:
            body_out.append(
                "    %s *host_%s = (%s *)PE_Translate(pe_%s, 1);\n"
                % (pointee, pname, pointee, pname)
            )
    out.append("".join(sig))
    out.append("".join(body_out))
    out.append("    /* verbatim body (src/%s.c) */\n" % name)
    out.append("\n")
    out.append(rewritten.strip("\n") + "\n\n")
    out.append("}\n")
    return "".join(out)


# ── driver ───────────────────────────────────────────────────────────────

def targets(only):
    names = []
    for fn in sorted(os.listdir(DECOMP_DIR)):
        if not fn.endswith("_port.c"):
            continue
        names.append(fn[:-len("_port.c")])
    if only:
        names = [n for n in names if n in only]
    return names


def generate_one(name, src_text, meta, defined):
    fn = find_function(src_text, name)
    is_ptr = fn is not None and any(p[2] for p in parse_params(fn[1]))
    if is_ptr:
        return generate_ptr(name, src_text, meta, defined)
    return generate_leaf(name, src_text, meta, defined)


def existing_boundary_callees(text):
    return set(
        re.findall(
            r"#define\s+(func_[0-9A-Fa-f]+)\(\.\.\.\)\s+PE_D_COMP_BOUNDARY", text
        )
    )


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="verify, write nothing")
    ap.add_argument("--only", action="append", default=[], help="one leaf name")
    ap.add_argument(
        "--allow-orphans",
        action="store_true",
        help="with --check, tolerate TUs that have no src/ leaf (the checked-in"
             " orphan manifest is the authority for those)",
    )
    ap.add_argument(
        "--update-orphans",
        action="store_true",
        help="rewrite tools/analysis/decomp_port_orphans.txt from the current tree",
    )
    args = ap.parse_args(argv)

    entries = parse_subsegments(CONFIG)
    meta = build_meta(entries)
    defined = collect_defined_symbols()

    names = targets(set(args.only))
    if args.only:
        missing = set(args.only) - set(names)
        if missing:
            raise SystemExit("unknown leaf(s): %s" % ", ".join(sorted(missing)))

    orphans = []
    changed = []
    stale = []
    failed = []
    for name in names:
        srcp = os.path.join(SRC_DIR, name + ".c")
        dstp = os.path.join(DECOMP_DIR, name + "_port.c")
        if not os.path.exists(srcp):
            orphans.append(name)
            continue
        if name not in meta:
            failed.append((name, "no config subsegment metadata"))
            continue
        src_text = open(srcp, encoding="utf-8").read()
        existing = open(dstp, encoding="utf-8").read()
        generated = generate_one(name, src_text, meta[name], defined)
        if generated == existing:
            continue
        # A mismatch is "stale" when the existing TU was produced with a
        # different implemented-symbol view: it replaces a callee prototype
        # with a shim marker but emits no boundary define, so the call binds
        # to a callee the current tree now implements.  Regeneration differs
        # only in that binding.
        markers = set(
            re.findall(
                r"/\* shimmed by pe_guest_decomp\.h: (func_[0-9A-Fa-f]+) \*/",
                existing,
            )
        )
        boundary_defs = existing_boundary_callees(existing)
        if markers - boundary_defs:
            stale.append((name, sorted(markers - boundary_defs)))
            if not args.check:
                open(dstp, "w", encoding="utf-8").write(generated)
            continue
        used_callees = set(CALL_RE.findall(src_text)) - {name}
        forced = defined - used_callees
        if generate_one(name, src_text, meta[name], forced) == existing:
            boundary_now = sorted(used_callees & defined)
            stale.append((name, boundary_now))
            if not args.check:
                open(dstp, "w", encoding="utf-8").write(generated)
            continue
        changed.append(name)
        if not args.check:
            open(dstp, "w", encoding="utf-8").write(generated)

    print("targets: %d" % len(names))
    print("orphans (no src/ leaf, cannot regenerate): %d" % len(orphans))
    for n in orphans:
        print("  orphan %s" % n)
    print("stale boundaries (callee is now implemented): %d" % len(stale))
    for n, cals in stale:
        print("  stale %s (boundary: %s)" % (n, ", ".join(cals)))
    print("mismatched (regeneration differs): %d" % len(changed))
    for n in changed:
        print("  mismatch %s" % n)
    if failed:
        print("errors: %d" % len(failed))
        for n, why in failed:
            print("  error %s: %s" % (n, why))
    if args.update_orphans:
        with open(ORPHANS_FILE, "w", encoding="utf-8") as fh:
            fh.write("# pc_port/game/decomp TUs with no matching src/ leaf.\n")
            fh.write("# Machine-checked by tools/analysis/gen_decomp_ports.py"
                     " and the decomp-port regression test.\n")
            for n in orphans:
                fh.write(n + "\n")
        print("wrote %s (%d entries)" % (ORPHANS_FILE, len(orphans)))

    if args.check:
        bad = len(changed) + len(stale) + len(failed)
        if args.allow_orphans:
            expected = read_orphan_manifest()
            new = sorted(set(orphans) - expected)
            fixed = sorted(expected - set(orphans))
            if new:
                print("new orphans (not in %s): %d" % (ORPHANS_FILE, len(new)))
                for n in new:
                    print("  new-orphan %s" % n)
                bad += len(new)
            if fixed:
                print("manifest entries that now have a src/ leaf: %d" % len(fixed))
                for n in fixed:
                    print("  fixed %s" % n)
                bad += len(fixed)
        else:
            bad += len(orphans)
        print("check: %s" % ("FAIL" if bad else "OK"))
        return 1 if bad else 0
    print("wrote %d file(s)" % (len(names) - len(orphans) - len(failed)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
