#!/usr/bin/env python3
"""m2c_leaf.py — first-draft candidate C for a retail function, via m2c.

This is a *triage accelerator*, not an authority. It extracts one function's
assembly from the splat output in `asm/disc1/`, runs the m2c decompiler
(https://github.com/matt-kempster/m2c, fetched by `scripts/setup_m2c.sh`) with
the GCC-MIPS target this project uses, and writes the candidate C to
`build/m2c_candidates/<name>.c`. The candidate still has to be made to compile
byte-identically by `tools/analysis/try_leaf.py` and, finally, by
`scripts/build_us.sh` — only that fresh build is matching evidence.

The value is that m2c recovers control flow, stack frame layout, and field
offsets in seconds, so the human/agent effort drops to fixing codegen choices
(declaration order, pointer arithmetic form, `-O` level, maspsx gates) rather
than re-deriving the whole function from raw MIPS.

Usage:
    python3 tools/analysis/m2c_leaf.py NAME [NAME ...]        # write candidates
    python3 tools/analysis/m2c_leaf.py --print NAME           # to stdout
    python3 tools/analysis/m2c_leaf.py --try NAME             # run try_leaf too
    python3 tools/analysis/m2c_leaf.py --from-file list.txt

The `--try` path needs the function's file offset and size, which are read
from `build/asm_worklist.json` (run `tools/analysis/asm_function_worklist.py`
first). Candidates are never written into `src/` — that stays a human decision.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ASM_DIR = ROOT / "asm/disc1"
M2C_SRC = ROOT / "tools/era/m2c"
M2C_PY = M2C_SRC / "m2c.py"
M2C_PYTHON = ROOT / "tools/era/m2c-venv/bin/python"
OUT_DIR = ROOT / "build/m2c_candidates"
CTX_PATH = ROOT / "build/m2c_context.h"

NONMATCHING_RE = re.compile(r"^nonmatching\s+(\S+),", re.M)

# Retail access widths, used to type the m2c context. `op $r,%lo(SYM)($r)` and
# `op $r,0xNNN($gp)` are the two shapes cc1 emits for globals.
ACCESS_WIDTH = {
    "lw": 4, "sw": 4,
    "lh": 2, "lhu": 2, "sh": 2,
    "lb": 1, "lbu": 1, "sb": 1,
}
WIDTH_C_TYPE = {1: "unsigned char", 2: "unsigned short", 4: "unsigned int"}
SYMBOL_ACCESS_RE = re.compile(
    r"\b(lw|sw|lh|lhu|sh|lb|lbu|sb)\s+\$\w+,\s*%lo\((\w+)\)\(\$\w+\)"
)
GP_ACCESS_RE = re.compile(
    r"\b(lw|sw|lh|lhu|sh|lb|lbu|sb)\s+\$\w+,\s*(0x[0-9A-Fa-f]+)\(\$gp\)"
)
# Retail's $gp base (see DECOMP_COVERAGE_CEILING.md / ACTIVE_HANDOFF.md).
GP_BASE = 0x8009CD70
SYMBOL_RE = re.compile(r"\b(D_[0-9A-Fa-f]{6,8})\b")
FUNC_RE = re.compile(r"\b(func_[0-9A-Fa-f]{8})\b")


def build_worklist_index() -> dict[str, dict]:
    path = ROOT / "build/asm_worklist.json"
    if not path.is_file():
        return {}
    entries = json.loads(path.read_text()).get("worklist", [])
    return {e["name"]: e for e in entries}


def unit_for(name: str, index: dict[str, dict]) -> str | None:
    if name in index:
        return index[name]["unit"]
    for path in sorted(ASM_DIR.glob("*.s")):
        text = path.read_text(errors="ignore")
        if re.search(r"^nonmatching\s+" + re.escape(name) + r"\b", text, re.M):
            return path.stem
    return None


def generate_context() -> Path:
    """Declare every D_* global with the width retail actually accesses it at.

    m2c produces noticeably cleaner output when it knows a symbol is a global,
    so it stops inventing a `saved_reg_gp` pseudo-struct. Giving each global the
    WIDTH retail loads/stores through makes the draft's accesses the right size
    too — an agent found this nearly halved the diff on the 8.6 KB battle tick
    (`docs/evidence/bigfish-1d340/`). Widths come from the disassembly itself:
    `lw/sw` = 4, `lh/lhu/sh` = 2, `lb/lbu/sb` = 1. A symbol accessed at more
    than one width keeps the most common one, widest on a tie.
    """
    names: set[str] = set()
    funcs: set[str] = set()
    widths: dict[str, dict[int, int]] = {}

    def note(symbol: str, width: int) -> None:
        widths.setdefault(symbol, {})[width] = (
            widths.setdefault(symbol, {}).get(width, 0) + 1
        )

    for path in sorted(ASM_DIR.glob("*.s")):
        text = path.read_text(errors="ignore")
        names.update(SYMBOL_RE.findall(text))
        funcs.update(FUNC_RE.findall(text))
        # absolute / symbol-relative: op $r,%lo(SYM)($r)
        for op, sym in SYMBOL_ACCESS_RE.findall(text):
            note(sym, ACCESS_WIDTH[op])
        # gp-relative: op $r,0xNNN($gp)  -> resolve to D_<vram>
        for op, off in GP_ACCESS_RE.findall(text):
            if off is None:
                continue
            addr = GP_BASE + int(off, 16)
            if 0 <= addr <= 0xFFFFFFFF:
                note(f"D_{addr:08X}", ACCESS_WIDTH[op])

    lines = ["/* Generated by tools/analysis/m2c_leaf.py — m2c type context. */"]
    for n in sorted(names):
        seen = widths.get(n)
        if seen:
            width = max(seen, key=lambda w: (seen[w], w))
        else:
            width = 1
        lines.append(f"extern {WIDTH_C_TYPE[width]} {n};")
    # gp-resolved names may not appear literally in the asm text
    for n in sorted(set(widths) - names):
        seen = widths[n]
        width = max(seen, key=lambda w: (seen[w], w))
        lines.append(f"extern {WIDTH_C_TYPE[width]} {n};")
    for f in sorted(funcs):
        lines.append(f"s32 {f}();")
    CTX_PATH.parent.mkdir(parents=True, exist_ok=True)
    CTX_PATH.write_text("\n".join(lines) + "\n")
    return CTX_PATH


def build_gp_widths() -> dict[int, int]:
    """Map a `$gp` offset to the width retail accesses it at."""
    out: dict[int, int] = {}
    for path in sorted(ASM_DIR.glob("*.s")):
        for op, off in GP_ACCESS_RE.findall(path.read_text(errors="ignore")):
            out[int(off, 16)] = ACCESS_WIDTH[op]
    return out


GP_UNK_RE = re.compile(r"saved_reg_gp->unk([0-9A-Fa-f]+)")


def rewrite_saved_reg_gp(text: str) -> str:
    """Turn m2c's `saved_reg_gp->unkNNN` into the real `D_<vram>` global.

    m2c cannot know retail's `$gp` base, so every gp-relative access comes out
    as a field of its invented `saved_reg_gp` pseudo-struct, which then does not
    compile. The offsets are unambiguous, so they are mapped back to the
    `D_<vram>` symbol at `0x8009CD70 + offset`, with the width retail used.
    Symbols that m2c dereferences are declared pointer-typed instead.
    """
    widths = build_gp_widths()
    if not widths:
        return text

    used: dict[str, int] = {}

    def repl(m: re.Match) -> str:
        offset = int(m.group(1), 16)
        if offset not in widths:
            return m.group(0)
        name = f"D_{GP_BASE + offset:08X}"
        used.setdefault(name, widths[offset])
        return name

    text = GP_UNK_RE.sub(repl, text)
    if not used:
        return text

    pointer_used = {
        name for name in used if re.search(rf"\b{name}\s*(?:->|\[)", text)
    }
    decls = []
    for name, width in sorted(used.items()):
        if name in pointer_used and width == 4:
            decls.append(f"extern void *{name};")
        else:
            decls.append(f"extern {WIDTH_C_TYPE[width]} {name};")
    return "\n".join(decls) + "\n\n" + text


def run_m2c(name: str, unit: str, context: Path | None) -> str:
    cmd = [
        str(M2C_PYTHON),
        str(M2C_PY),
        "-t",
        "mips-gcc-c",
        "--globals",
        "used",
        "-f",
        name,
    ]
    if context is not None:
        cmd += ["--context", str(context)]
    cmd.append(str(ASM_DIR / f"{unit}.s"))
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        return f"/* m2c failed for {name}: {proc.stderr.strip()} */\n"
    return rewrite_saved_reg_gp(proc.stdout)


def run_try_leaf(name: str, source: Path, index: dict[str, dict]) -> None:
    entry = index.get(name)
    if not entry:
        print(f"  (no worklist entry for {name}; skipping --try)", file=sys.stderr)
        return
    vram = int(name[5:], 16)
    offset = vram - 0x8000F800
    cmd = [
        sys.executable,
        str(ROOT / "tools/analysis/try_leaf.py"),
        str(source),
        hex(offset),
        hex(entry["size"]),
    ]
    print(f"  $ {' '.join(cmd)}")
    subprocess.run(cmd)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("names", nargs="*")
    ap.add_argument("--from-file", help="read function names, one per line")
    ap.add_argument("--print", action="store_true", help="print instead of writing")
    ap.add_argument("--try", dest="try_leaf", action="store_true",
                    help="also run try_leaf.py")
    ap.add_argument("--no-context", action="store_true")
    ap.add_argument("--out-dir", default=str(OUT_DIR))
    args = ap.parse_args()

    names = list(args.names)
    if args.from_file:
        names += [
            line.split()[0]
            for line in Path(args.from_file).read_text().splitlines()
            if line.strip() and not line.startswith("#")
        ]
    if not names:
        ap.error("no function names given")

    if not M2C_PY.is_file() or not M2C_PYTHON.is_file():
        print("m2c is not installed; run scripts/setup_m2c.sh", file=sys.stderr)
        return 2

    index = build_worklist_index()
    context = None if args.no_context else generate_context()
    out_dir = Path(args.out_dir)

    failures = 0
    for name in names:
        unit = unit_for(name, index)
        if unit is None:
            print(f"{name}: no splat asm found (is asm/disc1 split?)", file=sys.stderr)
            failures += 1
            continue
        text = run_m2c(name, unit, context)
        if text.startswith("/* m2c failed"):
            print(f"{name}: {text.strip()}", file=sys.stderr)
            failures += 1
            continue
        if args.print:
            print(f"/* ==== {name} ({unit}.s) ==== */")
            print(text)
            continue
        out_dir.mkdir(parents=True, exist_ok=True)
        dest = out_dir / f"{name}.c"
        dest.write_text(text)
        try:
            shown = dest.relative_to(ROOT)
        except ValueError:
            # --out-dir may point outside the repo; relative_to would raise.
            shown = dest
        print(f"{name}: {unit}.s -> {shown}")
        if args.try_leaf:
            run_try_leaf(name, dest, index)

    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
