#!/usr/bin/env python3
"""m2c_leaf.py — first-draft candidate C for a retail function, via m2c.

This is a *triage accelerator*, not an authority. It extracts one function's
assembly from the splat output in `asm/disc1/`, runs the m2c decompiler
(https://github.com/matt-kempster/m2c, fetched by `scripts/setup_m2c.sh`) with
the GCC-MIPS target this project uses, and writes the candidate C to
`build/m2c_candidates/<name>.c`. The candidate still has to be made to compile
byte-identically by `tools/analysis/try_leaf.py` and, finally, by
`scripts/build_us.sh` — only that fresh build is matching evidence.

The value is that m2c recovers control flow, stack frame layout, and field
offsets in seconds, so the human/agent effort drops to fixing codegen choices
(declaration order, pointer arithmetic form, `-O` level, maspsx gates) rather
than re-deriving the whole function from raw MIPS.

Usage:
    python3 tools/analysis/m2c_leaf.py NAME [NAME ...]        # write candidates
    python3 tools/analysis/m2c_leaf.py --print NAME           # to stdout
    python3 tools/analysis/m2c_leaf.py --try NAME             # run try_leaf too
    python3 tools/analysis/m2c_leaf.py --from-file list.txt

The `--try` path needs the function's file offset and size, which are read
from `build/asm_worklist.json` (run `tools/analysis/asm_function_worklist.py`
first). Candidates are never written into `src/` — that stays a human decision.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ASM_DIR = ROOT / "asm/disc1"
M2C_SRC = ROOT / "tools/era/m2c"
M2C_PY = M2C_SRC / "m2c.py"
M2C_PYTHON = ROOT / "tools/era/m2c-venv/bin/python"
OUT_DIR = ROOT / "build/m2c_candidates"
CTX_PATH = ROOT / "build/m2c_context.h"

NONMATCHING_RE = re.compile(r"^nonmatching\s+(\S+),", re.M)
SYMBOL_RE = re.compile(r"\b(D_[0-9A-Fa-f]{6,8})\b")
FUNC_RE = re.compile(r"\b(func_[0-9A-Fa-f]{8})\b")


def build_worklist_index() -> dict[str, dict]:
    path = ROOT / "build/asm_worklist.json"
    if not path.is_file():
        return {}
    entries = json.loads(path.read_text()).get("worklist", [])
    return {e["name"]: e for e in entries}


def unit_for(name: str, index: dict[str, dict]) -> str | None:
    if name in index:
        return index[name]["unit"]
    for path in sorted(ASM_DIR.glob("*.s")):
        text = path.read_text(errors="ignore")
        if re.search(r"^nonmatching\s+" + re.escape(name) + r"\b", text, re.M):
            return path.stem
    return None


def generate_context() -> Path:
    """Declare every D_* global and func_* as an opaque u8/s32.

    m2c produces noticeably cleaner output when it knows a symbol is a global,
    so it stops inventing a `saved_reg_gp` pseudo-struct.
    """
    names: set[str] = set()
    funcs: set[str] = set()
    for path in sorted(ASM_DIR.glob("*.s")):
        text = path.read_text(errors="ignore")
        names.update(SYMBOL_RE.findall(text))
        funcs.update(FUNC_RE.findall(text))
    lines = ["/* Generated by tools/analysis/m2c_leaf.py — m2c type context. */"]
    for n in sorted(names):
        lines.append(f"extern u8 {n};")
    for f in sorted(funcs):
        lines.append(f"s32 {f}();")
    CTX_PATH.parent.mkdir(parents=True, exist_ok=True)
    CTX_PATH.write_text("\n".join(lines) + "\n")
    return CTX_PATH


def run_m2c(name: str, unit: str, context: Path | None) -> str:
    cmd = [
        str(M2C_PYTHON),
        str(M2C_PY),
        "-t",
        "mips-gcc-c",
        "--globals",
        "used",
        "-f",
        name,
    ]
    if context is not None:
        cmd += ["--context", str(context)]
    cmd.append(str(ASM_DIR / f"{unit}.s"))
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        return f"/* m2c failed for {name}: {proc.stderr.strip()} */\n"
    return proc.stdout


def run_try_leaf(name: str, source: Path, index: dict[str, dict]) -> None:
    entry = index.get(name)
    if not entry:
        print(f"  (no worklist entry for {name}; skipping --try)", file=sys.stderr)
        return
    vram = int(name[5:], 16)
    offset = vram - 0x8000F800
    cmd = [
        sys.executable,
        str(ROOT / "tools/analysis/try_leaf.py"),
        str(source),
        hex(offset),
        hex(entry["size"]),
    ]
    print(f"  $ {' '.join(cmd)}")
    subprocess.run(cmd)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("names", nargs="*")
    ap.add_argument("--from-file", help="read function names, one per line")
    ap.add_argument("--print", action="store_true", help="print instead of writing")
    ap.add_argument("--try", dest="try_leaf", action="store_true",
                    help="also run try_leaf.py")
    ap.add_argument("--no-context", action="store_true")
    ap.add_argument("--out-dir", default=str(OUT_DIR))
    args = ap.parse_args()

    names = list(args.names)
    if args.from_file:
        names += [
            line.split()[0]
            for line in Path(args.from_file).read_text().splitlines()
            if line.strip() and not line.startswith("#")
        ]
    if not names:
        ap.error("no function names given")

    if not M2C_PY.is_file() or not M2C_PYTHON.is_file():
        print("m2c is not installed; run scripts/setup_m2c.sh", file=sys.stderr)
        return 2

    index = build_worklist_index()
    context = None if args.no_context else generate_context()
    out_dir = Path(args.out_dir)

    failures = 0
    for name in names:
        unit = unit_for(name, index)
        if unit is None:
            print(f"{name}: no splat asm found (is asm/disc1 split?)", file=sys.stderr)
            failures += 1
            continue
        text = run_m2c(name, unit, context)
        if text.startswith("/* m2c failed"):
            print(f"{name}: {text.strip()}", file=sys.stderr)
            failures += 1
            continue
        if args.print:
            print(f"/* ==== {name} ({unit}.s) ==== */")
            print(text)
            continue
        out_dir.mkdir(parents=True, exist_ok=True)
        dest = out_dir / f"{name}.c"
        dest.write_text(text)
        try:
            shown = dest.relative_to(ROOT)
        except ValueError:
            # --out-dir may point outside the repo; relative_to would raise.
            shown = dest
        print(f"{name}: {unit}.s -> {shown}")
        if args.try_leaf:
            run_try_leaf(name, dest, index)

    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
